### ISSUE TITLE
Attachment Support

### ISSUE THREAD

**Issue by Lvl4Sword** [chatch/stellarexplorer#105]
https://www.stellar.org/developers/guides/attachment.html

**Comment by chatch** [comment]
Attachments are supported in that the sha256 memo hash is shown on the transaction view. For example see this testnet transaction: http://testnet.local:3000/tx/68c11bcef9d9b9155f62d522407880d428328ba0298a6fc0cb550e54936f881c

**Comment by chatch** [comment]
The attachment contents or URL (if there is one) of the actual attachment content are unknown to stellar explorer so can't be shown. Usually it'll be private between the sender and receiver as in the compliance protocol.
