### ISSUE TITLE
error.unknown

### ISSUE THREAD

**Issue by kenneth** [chatch/stellarexplorer#107]
yarn start have error,and what's wrong?

**Comment by chatch** [comment]
what's the error? i typically use npm although I can't think off the top of my head why yarn may not work...

**Comment by kenneth** [comment]
@chatch no problem i node version use wrong.

**Comment by chatch** [comment]
apologies for the very late reply on this.  sounds like your trying to run your own local backend ?

see details here for configuring hosts and running in local dev.
