### ISSUE TITLE
Switching XlM to bitbns but forget to enter memo and not received stellar

### ISSUE THREAD

**Issue by okluvme** [chatch/stellarexplorer#109]
Please suggest me how to short out this problem I am not be able to understand anything help me 
![Screenshot_20190421-133336](https://user-images.githubusercontent.com/49831315/56467581-77abab80-643e-11e9-97a0-f7154bf8c7e5.png)

**Comment by chatch** [comment]
you'll need to talk to koinex if you havn't received it but is the destination address in that transaction yours?

**Comment by alidindarlou** [comment]
Hello
 I bought 600 units xlm on May 16, 2019, but I unfortunately forgot to enter the tag. Thank you for helping us;
 with the wallet address is:
GAN5X2FUP2PCQITFAZE2CB5PBTGVZKVJLUDVTRRRV7PTZYQWYD4CRP65
Tag: 2177486079300221

**Comment by chatch** [comment]
ok, just to be clear i can't help retrieve your funds, steexp is just a view of the ledger. 

from what i understand in the issue description koinex has sent funds to your address - if you own the withdrawal address you can access the funds and if not you can't ...

**Comment by okluvme** [comment]
Now I receaved
