### ISSUE TITLE
Can't activate my ledger account

### ISSUE THREAD

**Issue by nalperov** [chatch/stellarexplorer#110]
In order to activate my account I need to submit at leat 1 lumen.
I withdrawal 21 lumens from Binance to my public key:
GDIGB5USVPHPMN4KHCJSPUUU6ZLJGJ6LORB5EOTHAUUAQJHHP5DBK74C

The transaction can't be made. It is in status processing and seems like that my public key can't be found. Binance recieved an erro error.cant.find.

Plrease support to activate my account

**Comment by chatch** [comment]
steexp.com is just read only view of the network so I couldn't have done anything with your account.  but looking at your address it appears it worked in the end?
