### ISSUE TITLE
Support Protocol 11

### ISSUE THREAD

**Issue by chatch** [chatch/stellarexplorer#111]
see here https://www.stellar.org/blog/protocol-11-improvements-stellar

Updates for the new protocol. Ensure old ledger entries still render okay but support the new data in protocol 11 also.

support rendering of the new operations and ensure offers views show the new offer details
show the operations per ledger limit
fix the transactions counts on the ledger views (it's blank now since a recent changes)
new fee details on transactions - is horizon now providing the submitted maximum fee?

**Comment by chatch** [comment]
upgrade to latest stellar-sdk

**Comment by chatch** [comment]
closing - updates made.

**Comment by nanis94** [comment]
#111 master

**Comment by nanis94** [comment]
#111 main
