### ISSUE TITLE
transfer

### ISSUE THREAD

**Issue by Gmm0320** [chatch/stellarexplorer#113]
GCEBWUW5OIJIOJMYVXVBWHXH4JG72IQZV25ZGWPCFYVDWOAOMXKHRHMK
--
balance

I transfered Stellar  XLM how do I transfer it to my stellar account viewer
Thanks 
for any help 
Gary

**Comment by hawarri20** [comment]
I did not understand your intent possible clarification

**Comment by Gmm0320** [comment]
I had transfered 2557.98 XLM from binance to Stellar explorer  on 05/23/2019 I am not sure what exactly I done but I have a Stellar acct that I use my Nano X to open I would like to transfer this GCEBWUW5OIJIOJMYVXVBWHXH4JG72IQZV25ZGWPCFYVDWOAOMXKHRHMK     to my account with stellar that I use with Nano X 
Thanks for helpGary  

    On Saturday, June 29, 2019, 08:31:24 AM EDT, hawarri20 <notifications@github.com> wrote:  
 
 I did not understand your intent possible clarification

**Comment by chatch** [comment]
hi @Gmm0320, you withdrew from binance to this account GCEBWUW5OIJIOJMYVXVBWHXH4JG72IQZV25ZGWPCFYVDWOAOMXKHRHMK. and presumably you used some wallet software to setup this account?  or did you generate it some other way? if it was with some wallet, you just need to go to that wallet and create a transaction with a payment to your nano x address.  does that make sense?

btw. to be clear stellar explorer is just a read only view of the ledger. so you can't transfer "to stellar explorer". you transfer to an account on the Stellar network and you can merely see that account and see that transfer operation with Stellar Explorer.

**Comment by Gmm0320** [comment]
Sorry I do not understand it is setting here I can not figure a way to transfer it to the nano x address
