### ISSUE TITLE
XLM not credited to account

### ISSUE THREAD

**Issue by P1968** [chatch/stellarexplorer#114]
Greetings,

I did a transfer; but the XLM is not being credited into my account.

Here is the information:
Transaction ID:
40cab5070ace627e80605135442df1ca00f0ddc56c3efd4831d757bd2d6a5efa

Address to credit:
GDQP2KPQGKIHYJGXNUIYOMHARUARCA7DJT5FO2FFOOKY3B2WSQHG4W37
Ledger
24571720
Memo
XLM
Amount
400.99

**Comment by mandy745** [comment]
I also transfered my stellar but not received on my account.Did u receive it.

**Comment by P1968** [comment]
I had to send the transaction ID to the receiving website (coinbase in my case).  They found it but it took 4 weeks.  You probably forgot to add the memo aspect of the transaction, as did i.

Patrick Delaney
202-746-2277

**Comment by mandy745** [comment]
Hi Patrick

I am realy thankfull for your response.

I did make transfer as for XLM in same way I do for other coins from
Coinbase and it gone through .  I never had an idea that it may need Memo
as I never used it.

I request you to kindly help me in getting this credited to my binance
account.  Plz let me know if you need any other information.

Regards

Kuldeep Mandial
