### ISSUE TITLE
XLM not credited to account

### ISSUE THREAD

**Issue by FritzFlo** [chatch/stellarexplorer#119]
I transfered 8300 XLM and it did not arrive at the account. How can I find out where the money went?

account sent to: GB6YPGW5JFMMP2QB2USQ33EUWTXVL4ZT5ITUNCY3YKVWOJPP57CANOF3

![Explorer](https://user-images.githubusercontent.com/53511117/62194308-e96a8e00-b379-11e9-842d-4e08ad67a2f7.JPG)

**Comment by chatch** [comment]
This is a bitrex account right?  are you withdrawing?  you'll need to ask bitrex about this.
