### ISSUE TITLE
Not credited

### ISSUE THREAD

**Issue by hiaiho** [chatch/stellarexplorer#121]
I have tried to transfer XLM but never received. Can you help me? Here the transaction number 578c717bd08d688927019d8676470661c94bff9eebd9a6944d1d6e0c232c950f thanks a lot

**Comment by chatch** [comment]
hi @hiaiho steexp is just a view of the ledger. if this transaction was sent to the wrong address nothing can be done to recover the funds except find the owner of the destination if there is one..

**Comment by hiaiho** [comment]
Hi, thanks for the feedback. I copied and pasted the info from coinbase account andfollowed  the instructions.

It worked for ethereum and DAI. 
I see many people having issues with the XLM and i think this is not a good way to start the use of this feature if it is so easy to lose money.

Can i do anything?
Thanks
