### ISSUE TITLE
XLM TRANSFERED BUT NOT RECEIVEDIN MY ACCOUNT.

### ISSUE THREAD

**Issue by mandy745** [chatch/stellarexplorer#122]
Transfered 998.98 XLM stellar  on July 27, 2019 

Transaction id : 

2CE8622BB37AA38C6150081DCF4FD5E25A636838AD4F82630B2068229CD13A87

Destination address: Binance

GAHK7EEG2WWHVKDNT4CEQFZGKF2LGDSW2IVM4S5DP42RBW3K6BTODB4A

These stellar are still not received..????

**Comment by Kellog19** [comment]
This is mine.   I was sending it to my duckdice account.   And I still haven’t received it

**Comment by chatch** [comment]
you have to ask binance about this. 

btw. steexp is just a view of the ledger.
