### ISSUE TITLE
How to show only asset balance (only value) 

### ISSUE THREAD

**Issue by ccuniverseuvumaniac** [chatch/stellarexplorer#126]
Hello how to make a page with only balance for asset?

**Comment by ccuniverseuvumaniac** [comment]
https://steexp.com/account/GC6SSKECVGUSZ2LDS5I2UG5JRTA3IHVN3T66J3XKUOOONIWI6Z7QHL5I

i want have only UVU balance in number at new site...

**Comment by chatch** [comment]
there is no view in steexp that shows just the one balance. the account view on steexp lists all balances for the account.

**Comment by ccuniverseuvumaniac** [comment]
yes but coinmarketcap wants only value of my token in numbers to create or build that url site

**Comment by chatch** [comment]
they can't use the horizon link and pull out the value from the JSON?  then i guess you have to deploy your own endpoint that does that and serves up just the balance ...

**Comment by ccuniverseuvumaniac** [comment]
> 
> 
> they can't use the horizon link and pull out the value from the JSON? then i guess you have to deploy your own endpoint that does that and serves up just the balance ...

https://ccuniverse.org/balance.php

i got it
