### ISSUE TITLE
Where's my Lumens?

### ISSUE THREAD

**Issue by goatincharge** [chatch/stellarexplorer#129]
Transaction ID

8696930BCB10A92F8304535D19D1B2AAFB1B26D4FDAE2344F15D6D10860D8C13JSON

The memo text seems to have two lines in front of it. It's that why I didn't see my 36.4 Lumens show up in my coinbase even though it's complete on the stellar network?

Hope do I access my Lumens?

I lost 74 the first time I lost Lumens and now 36.4! I want my Lumens back!!!!

**Comment by chatch** [comment]
Who did you send it to? You'll probably need to contact them if it's not processed.

Can you send a link to your transaction on steexp? i can't find the above tx id...

**Comment by alexkastefa** [comment]
Transaction
0b628cf4a759532aca1d6e395c831899ebd40ada6f3f9741831cbb44a56431ee
Hello
I didn't put the memo and I lost the stellar

**Comment by chatch** [comment]
who is the receiver GDQP2KPQGKIHYJGXNUIYOMHARUARCA7DJT5FO2FFOOKY3B2WSQHG4W37 ?  is it an exchange?

**Comment by alexkastefa** [comment]
Receiver GATUGRS3JZIRO4JSWEBK5KJTQZ6NAQECKYBKV7QRE5L6ATKLE6O7RPI4

**Comment by chatch** [comment]
sorry i have no visibility into this. i don't know who owns these accounts ...  if you can contact the reciever then maybe they can help you.
