### ISSUE TITLE
Stellar

### ISSUE THREAD

**Issue by Desperado811** [chatch/stellarexplorer#132]
Please tell me how long are the tokens from the wallet to the exchange? It's been 4 hours but the tokens have not come

 tx id -  746360b66220d48e36c3f8c6b61eec518b512c6874b59ad0fc65e716bd43d9e7

**Comment by chatch** [comment]
you'll need to ask binance about this. on the Stellar network it only takes a few seconds however Binance will take some time to process the transaction to your account.

**Comment by Desperado811** [comment]
Thanks, everything came

пн, 25 нояб. 2019 г., 10:40 Chris Hatch <notifications@github.com>:
