### ISSUE TITLE
Lumens lost

### ISSUE THREAD

**Issue by srdracar** [chatch/stellarexplorer#133]
trans ıd F031CD6605CB4DC55FCD5F4FC43DC40EAB41DF7323FDBA7AF02C0A73D45CD488.Parıbu to binance.1596 lumens are lost. I wrote the memo code wrong

**Comment by srdracar** [comment]
![02220E89-76BA-4233-879D-1849AD2C6DF4](https://user-images.githubusercontent.com/58799764/70681739-740ab480-1cad-11ea-81c6-a2db76268e52.png)

**Comment by chatch** [comment]
if the destination was binance then you'll need to talk to them to resolve it.

steexp provides only a view of the network.
