### ISSUE TITLE
I have not received the XLM I have exchanged yet. transaction is incomplete. 

### ISSUE THREAD

**Issue by engchamara** [chatch/stellarexplorer#134]

**Comment by engchamara** [comment]
https://steexp.com/tx/81961a23530b6e5ac8966d54c43395305355cc7a3bf67ccd44abfa26c4188024         Transection hash

**Comment by chatch** [comment]
you'll need to ask binance about this.  steexp is just a view of the ledger.

**Comment by 9466862026** [comment]
I haven't received my XLM amount 219.99 and transaction id is TRANSACTION449144A0544EBCF31F589317DD96826679F0896E54806C51A81679B7A8B9A6A9JSON

**Comment by engchamara** [comment]
ok sir
