### ISSUE TITLE
I can't find my XLM -_-

### ISSUE THREAD

**Issue by RiedAA** [chatch/stellarexplorer#136]
Hey there I have transferred my XLM from my wallet to another account ( my coin account) and I didn't put memo now I see that my XLM are no longer on my wallet but nowhere to find em on my account help plz 
F6B5F8473EB5599F0FB726A6E35140BA135E6F1C87D03DFF57A22ABD8A24D184JSON
This is the transaction!

**Comment by chatch** [comment]
please check with the recipient. stellarexplorer is just a readonly view of the ledger.
