### ISSUE TITLE
I can't find my XLM

### ISSUE THREAD

**Issue by psymanmaster** [chatch/stellarexplorer#137]
Hey there I have transferred my XLM from my wallet to another account ( my coin account) and I didn't put memo now I see that my XLM are no longer on my wallet but nowhere to find em on my account help plz
My wallet is:
GA7X7UER4YSMB5LCM7UCULETW5GNDF22TVZPBMGOV5QV2YJBS5FI5GG4
And i send it to this wallet:
GB67TJFJO3GUA432EJ4JTODHFYSBTM44P4XQCDOFTXJNNPV2UKUJYVBF

THANK YOU WHERY MUCH!!!

**Comment by psymanmaster** [comment]
Anyone?

**Comment by chatch** [comment]
please check with the receipient. stellarexplorer is just a readonly view of the ledger.
