### ISSUE TITLE
XLM Sending error

### ISSUE THREAD

**Issue by therealbigdaddy1961** [chatch/stellarexplorer#141]
###  Please NOTE the following before creating an issue:

* stellarexplorer ([steexp.com](https://steexp.com)) is a readonly view of the Stellar ledger so we can't help retrieve lost funds
* if your having trouble locating funds sent to an exchange (eg. Binance), contact the exchange directly
* if you entered an incorrect memo or forgot to enter your memo, we unfortunately can't help. contact the recipient and tell them your sending address

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

## Issue Description
Hi. On 2/11/2020 I attempted to send some XLM from Coinbase Wallet to Coinbase.com. This was my first attempt at doing something like this and I thought I had followed the instructions well, but apparently I did not. My lack of experience/knowledge resulted in, apparently, my XLM being sent here and I have no idea how to retrieve it to send it to Coinbase. HELP!!!!!

**Comment by chatch** [comment]
please read the points under "Please NOTE the following before creating an issue" above. we can't do anything.
