### ISSUE TITLE
f9fe8ae54f15c6eae5dc36a7906f45e15b1a89ee04d160dc45080b6142236a0b

### ISSUE THREAD

**Issue by gbc350** [chatch/stellarexplorer#142]
###  Please NOTE the following before creating an issue:

I have sent money to another wallet that did not receive and want to get funds back in my wallet. 

f9fe8ae54f15c6eae5dc36a7906f45e15b1a89ee04d160dc45080b6142236a0b

* stellarexplorer ([steexp.com](https://steexp.com)) is a readonly view of the Stellar ledger so we can't help retrieve lost funds
* if your having trouble locating funds sent to an exchange (eg. Binance), contact the exchange directly
* if you entered an incorrect memo or forgot to enter your memo, we unfortunately can't help. contact the recipient and tell them your sending address

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

**Comment by chatch** [comment]
please read the points under "Please NOTE the following before creating an issue" above.
