### ISSUE TITLE
GC76EBRROA6DWMCCVPZZYHU3HHNOBHHTGFQYEOEVQLWHVDCDC5YJZ5QK

### ISSUE THREAD

**Issue by piposan** [chatch/stellarexplorer#145]
Hi there, looking to retrieve an old wallet history but seems it's no longer available on the explorer. I think I may have also still had some Mobi stored in this wallet too!

**Comment by chatch** [comment]
Do you mean the account was removed? Yes stellarexplorer only shows current data unfortunately. Try stellar.expert if you want to see historical data for an old account.
