### ISSUE TITLE
I had sent my XLM to my ledger x with the same address code that i been using and haven't received it yet.

### ISSUE THREAD

**Issue by mbrooks007** [chatch/stellarexplorer#148]
![Screenshot_20200714-075804_Samsung Internet](https://user-images.githubusercontent.com/68279327/87423308-170b1000-c5a8-11ea-97bf-5ebd2c1cbda5.jpg)
###  Please NOTE the following before creating an issue:

* stellarexplorer ([steexp.com](https://steexp.com)) is a readonly view of the Stellar ledger so we can't help retrieve lost funds
* if your having trouble locating funds sent to an exchange (eg. Binance), contact the exchange directly
* if you entered an incorrect memo or forgot to enter your memo, we unfortunately can't help. contact the recipient and tell them your sending address

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

## Issue Description
Jump to bottom

I had sent my XLM to my ledger x with the same address code that i been using and haven't received it yet. 

And this is the address I used GAG6PAJWSHVZ7WID2SDKX2ZTRZ55GJDQ6YC5NSIJ5LPN4FUOWOVMXRTX

**Comment by chatch** [comment]
steexp can only show the transaction. you might need to contact ledger support?
