### ISSUE TITLE
I sent Stellar to my Nano ledger X, I have not received them, Nano Ledger is updated and Sync well. 

### ISSUE THREAD

**Issue by stellarcheck** [chatch/stellarexplorer#150]
![2020-07-15 Stellar](https://user-images.githubusercontent.com/68358686/87614418-d523bc00-c6c4-11ea-89d1-5c05bf4d0907.png)
![image](https://user-images.githubusercontent.com/68358686/87615546-d30f2c80-c6c7-11ea-8c54-a06ebdfc661b.png)

###  Please NOTE the following before creating an issue:

* stellarexplorer ([steexp.com](https://steexp.com)) is a readonly view of the Stellar ledger so we can't help retrieve lost funds
* if your having trouble locating funds sent to an exchange (eg. Binance), contact the exchange directly
* if you entered an incorrect memo or forgot to enter your memo, we unfortunately can't help. contact the recipient and tell them your sending address

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

## Issue Description
It is not the first time I sent from the same platform to NANO ledger X, and it shows from all other previous transactions but the one on 06/25/2020 transaction does not show on nano Legder X. please review. the address were correct, checked on Binance for address, and it was also correct. what could happened?

**Comment by chatch** [comment]
sorry I don't know anything about NANO ledger X. can you ask their support?

**Comment by lyeslounn** [comment]
![Screenshot_20200715-140506_Samsung Internet](https://user-images.githubusercontent.com/68332471/87664176-1bc8f300-c765-11ea-81e8-9a163db615df.jpg)

Since one month i never received this transaction from wallet to exchange account...any help ? Thanks

**Comment by chatch** [comment]
you'll have to ask the exchange. steexp can just show the transaction.

**Comment by lyeslounn** [comment]
Merci !  Coinbase said to me they dont know..crazy situation.
Thank you

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________
