### ISSUE TITLE
Issue with deposit

### ISSUE THREAD

**Issue by ATBonn** [chatch/stellarexplorer#152]
So is it normal for Binance.us to not show a deposit even though the transaction was confirmed and double checked to be correct? 7 hours now and still no deposit being shown. Not a very small amount either.

**Comment by dannator** [comment]
I’m having the same issue

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
