### ISSUE TITLE
coin not received

### ISSUE THREAD

**Issue by DrawXd** [chatch/stellarexplorer#154]
I send some stellar to my friend and he never received it, even though the transaction was completed 
transaction id

4fc870e639418512d95a00e1b00bac033173e453f21527811e57ec2a9c1457c5

transaction adress 

GAHK7EEG2WWHVKDNT4CEQFZGKF2LGDSW2IVM4S5DP42RBW3K6BTODB4A

10521625431052162543  transaction payment method
I already contacted binance and they did tell me that I should contact people here.

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
