### ISSUE TITLE
Coin not received 

### ISSUE THREAD

**Issue by Idriss13015** [chatch/stellarexplorer#156]
I send some stellar to my kraken account and i never received it, even though the transaction was completed

transaction id : 

7465D4E59224637201712D431D50EBE26072E43F9166236EE909565E915EC901

Here is my stellar export : 
id,"transactionSuccessful","sourceAccount","type","typeI","createdAt","transactionHash","assetType","from","to","amount"136859300390940673,"true","GDSHQUWDZU2XANCQDY6SRRA3YXLVEIBG3HRTTZFNWQMEGQWCZPERRTCP","payment","1","2020-09-30T07:44:09Z","7465d4e59224637201712d431d50ebe26072e43f9166236ee909565e915ec901","native","GDSHQUWDZU2XANCQDY6SRRA3YXLVEIBG3HRTTZFNWQMEGQWCZPERRTCP","GA5XIGA5C7QTPTWXQHY6MCJRMTRZDOSHR6EFIBNDQTCQHG262N4GGKTM","135.6851404"

Can you help me please ? 
Thank you.

**Comment by Idriss13015** [comment]
![Screenshot_20201117-231743_Chrome](https://user-images.githubusercontent.com/74106037/99457430-3f769280-292b-11eb-8b73-66ffa73adbcf.jpg)

**Comment by megaresk** [comment]
Same here

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
