### ISSUE TITLE
Coin not recieved

### ISSUE THREAD

**Issue by Vinsho** [chatch/stellarexplorer#157]
Hellou I sent some coins but they never arrived.
ID:
5ce39940004029ae58c35934b50b95c79c9729f3ad1cb6cd1653028e8ea5823c

Address:
GDQP2KPQGKIHYJGXNUIYOMHARUARCA7DJT5FO2FFOOKY3B2WSQHG4W37

Thank you very much

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
