### ISSUE TITLE
Issue with the transaction sent on Bitcoin.com 

### ISSUE THREAD

**Issue by kreproject** [chatch/stellarexplorer#159]
###  Please NOTE the following before creating an issue:

* stellarexplorer ([steexp.com](https://steexp.com)) is a readonly view of the Stellar ledger so we can't help retrieve lost funds
* if your having trouble locating funds sent to an exchange (eg. Binance), contact the exchange directly
* if you entered an incorrect memo or forgot to enter your memo, we unfortunately can't help. contact the recipient and tell them your sending address

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

## Issue Description

Hello,

I have an issue with this transaction below, sent with Bitcoin.com

I have opened a ticket with them too.

Can you check on your side ? 

https://steexp.com/error/not-found/0dd14985e45d48ab4e72965e53429a434070fcdd3f4c74e76ff3261620c6d335

Regards

Christophe

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
