### ISSUE TITLE
Externalise the anchors and exchanges data

### ISSUE THREAD

**Issue by chatch** [chatch/stellarexplorer#16]
We shouldn't need to redeploy the app whenever this metadata changes or when a new anchor launches.

Serve these files from somewhere or just make available on a seperate github project that can be fetched from the app ...

It might makes sense to generate most of this from a script that parses the server.toml files ... Have a script that runs periodically and checks if data has changed too.

**Comment by chatch** [comment]
see also directory in stellarterm https://github.com/irisli/stellarterm/blob/master/src/directory.js
this is basically the same set of data ...

**Comment by chatch** [comment]
use the stellarterm feed: https://github.com/irisli/stellarterm/issues/73

**Comment by irisli** [comment]
I'll comment here to notify you once the StellarTerm API is stable

**Comment by chatch** [comment]
thanks @irisli !

**Comment by irisli** [comment]
https://api.stellarterm.com/v1/ticker.json

Let me know how this ticker looks so far

**Comment by chatch** [comment]
that looks great. and yes really nice to show them in that ranking order. can I assume the assets always appear in the JSON in this descending activityScore order? I don't need to do a local sort on activityScore?

also i see you've got logos for all the assets in the repo. they all follow the <domain>.png naming convention right?

**Comment by irisli** [comment]
Yes, they will always be in the sorted order. The API is loosely modeled after coinmarketcap.com's API.

The png files are in the repo. But I think eventually I'll make the directory a package you can install via npm.

For now, just use this: https://github.com/irisli/stellarterm/blob/master/directory.json

The png files are actually in base64 encoded strings and you can just simply use it in something like `<img src={directory.assets['vcbear.net'].logo} />`

**Comment by irisli** [comment]
Oh! I just realized how to make the directory filesize smaller! I'll probably be able to cut it down to 50KB.

**Comment by irisli** [comment]
Also, I would suggest not using:
```
      "spread": 0.0694,
      "price_XLM": 15.292,
      "price_USD": 0.19013,
      "volume24h_XLM": 628705.45,
      "volume24h_USD": 7816.69,
      "depth10_XLM": 215837,
      "depth10_USD": 2683.5,
      "numBids": 20,
      "numAsks": 18,
```

Since there is a good chance i might change them

**Comment by irisli** [comment]
https://github.com/irisli/stellarterm/tree/master/directory

https://www.npmjs.com/package/stellarterm-directory

I've finally moved the stuff into its own directory!

**Comment by chatch** [comment]
cool stuff! i'll pull this in to the project.

**Comment by chatch** [comment]
deployed now using stellarterm directory to render the anchors
