### ISSUE TITLE
I transferred XLM binance to coinswich.

### ISSUE THREAD

**Issue by devendrasinh8844** [chatch/stellarexplorer#162]
I transferred XLM binance to coinswich.
And binance are transferred successful but not received in coinswich.
And talking with binance  but thay seid that we transferred.
Please help me

_Originally posted by @devendrasinh8844 in https://github.com/chatch/stellarexplorer/issues/161#issuecomment-735745045_

**Comment by Vives1611** [comment]
Hi, has your problem been solved? I have a similar problem

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
