### ISSUE TITLE
I had transferred XLM Binance to Coinswich..But my withdraw funds not credited. 

### ISSUE THREAD

**Issue by targetselva** [chatch/stellarexplorer#165]
[XLM Binance to coinswich..Binance shows completed..but my withdraw funds not credited..my attachment ](https://linksharing.samsungcloud.com/TzmlfRoLX64N) 
I transferred XLM binance to coinswich.
And binance are transferred successful but not received in coinswich.
And talking with binance but thay seid that we transferred.
Please help me

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
