### ISSUE TITLE
I had transferred XLM Binance to Coinswich. But my withdraw funds not credited..

### ISSUE THREAD

**Issue by targetselva** [chatch/stellarexplorer#166]
[XLM Binance to coinswich..Binance shows completed..but my withdraw funds not credited..my attachment](https://linksharing.samsungcloud.com/TzmlfRoLX64N) 
I transferred XLM binance to coinswich.
And binance are transferred successful but not received in coinswich.
And talking with binance but thay seid that we transferred.
Please help me..
My Txid:;8114f38906a13c1c8e88c0598d4420982f456c0b695a3df66a812d593169ef1c
My coinswich xlm address:GCVDIZAI4WBLH5WSZRMOIPIXBIBVJWGMFLZXK3DPXAX3VKOL4UEIQCAP

My memo:1032740

Please help me...please help me..please help me

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
