### ISSUE TITLE
Sent xlm from coinbasewallet to coinbase but it went to this site trying to transfer it back to cbasewallet

### ISSUE THREAD

**Issue by robert7616** [chatch/stellarexplorer#169]
###  Please NOTE the following before creating an issue:

* stellarexplorer ([steexp.com](https://steexp.com)) is a readonly view of the Stellar ledger so we can't help retrieve lost funds
* if your having trouble locating funds sent to an exchange (eg. Binance), contact the exchange directly
* if you entered an incorrect memo or forgot to enter your memo, we unfortunately can't help. contact the recipient and tell them your sending address

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this

**Comment by robert7616** [comment]
Ok so I can't sell or exchange from explorer saying it just stores
info.basically the crypto is lost an there's no way to get it back for
exchange to sell .so I just lose my crypto

**Comment by chatch** [comment]
can you talk to coinbase support about this? it's their systems the are either end of this transaction. can they fix it for you maybe?

**Comment by robert7616** [comment]
I'll try. Thanks
