### ISSUE TITLE
I sent XLM binance to altilly but I didn't received it

### ISSUE THREAD

**Issue by Vives1611** [chatch/stellarexplorer#172]
I have sent XLM from binance to altilly and I lost my all XLM. 
Address was correct and everything was correct then what happened.
Binance has told me that the transfer has been made and altilly that it has not received it, then it is a network problem!
I need my all XLM back

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
