### ISSUE TITLE
Issue with lost XLM after wallet renewal. NEED HELP

### ISSUE THREAD

**Issue by DmitryAKA** [chatch/stellarexplorer#173]
Have sent some XLM and after wallet renewal cannot find any of my coins at all.
Contacted Binance and they told to me that I need to contact with support here.

2018-01-13 17:27:33
XLM
1000.99
Completed
 
Address:
GCEZF2E4KE7MMAPIBU4OACCZIEP466Z65WV63FAYI3Q22OXY2RPVONGF

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
