### ISSUE TITLE
Issue with lost XLM

### ISSUE THREAD

**Issue by i7modi** [chatch/stellarexplorer#176]
![636223D5-B5AE-4724-8CC1-C1A3A9EF6853](https://user-images.githubusercontent.com/76993345/103620291-da85f480-4ef8-11eb-8c2c-3ff22226bf96.jpeg)

Issue with lost XLM I send it to my brother wallet and he didn’t receive anything please need help.

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
