### ISSUE TITLE
Unsure where my xlm has gone to. 

### ISSUE THREAD

**Issue by naphatali** [chatch/stellarexplorer#180]
Wanted to transfer my xlm from coinbase wallet to my coinspot wallet address. Have not been credited yet. Is there a waiting period? If so,how long on average? 

###  Please NOTE the following before creating an issue:

* stellarexplorer ([steexp.com](https://steexp.com)) is a readonly view of the Stellar ledger so we can't help retrieve lost funds
* if your having trouble locating funds sent to an exchange (eg. Binance), contact the exchange directly
* if you entered an incorrect memo or forgot to enter your memo, we unfortunately can't help. contact the recipient and tell them your sending address

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

**Comment by egansegal** [comment]
Did this issue get resolved? Si.ilar thing is happeing with me but sent from Binance to anotger wallet. Did it ever process? If not, what did you do?

**Comment by naphatali** [comment]
Hi there. Unfortunately the issue has not been resolved. I do hope yours will be. Thank you .

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
