### ISSUE TITLE
Where are my Stellar? Still can't find in my crypto wallet

### ISSUE THREAD

**Issue by arcio1982** [chatch/stellarexplorer#183]
I've just passed from Binance to Crypto.com a small amount of Stellar. Still can't find in my crypto wallet

**Comment by Grisgon** [comment]
I withdraw XLM wallet  from Bitkup to Binance, but it has not XLM in Binance wallet.

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
