### ISSUE TITLE
Sent 3000 Stellar without the correct Memo due to Coinbase and inexperience sending XLM

### ISSUE THREAD

**Issue by jcustodio318** [chatch/stellarexplorer#184]
![image](https://user-images.githubusercontent.com/77259843/104409351-f0a83c00-551a-11eb-8bc7-2ff7895e0ff4.png)

Transaction b892e34b8d4012866c1d11fc0d9552e5f567990a8300df0faf2103242898d128

I sent Stellar to Another Coinbase account not knowing a memo number was required. Coinbase made this very vague in their description box.  I've sent other crypto before thinking the address was the only requirement.  So instead I typed in "speedtest" in the memo box thinking it would send fast. Instead it took long.  I was waiting...and waiting.  It never arrived.  

I was wondering if that 3000 XLM could be sent back to the correct address and Memo.  Please Help its a lot of XLM.  

The Correct wallet Address and Memo is: 

GDQP2KPQGKIHYJGXNUIYOMHARUARCA7DJT5FO2FFOOKY3B2WSQHG4W37

2989908126

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
