### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by azbarroso** [chatch/stellarexplorer#191]
@chatch any clues on how to fix the failing build? I was trying on my local copy, but haven't found a solution yet.

**Comment by chatch** [comment]
hi @azbarroso , It's related to upgrades of packages recently. Most likely something has changed in a new React dependency but I haven't look into it so not sure ... So either reverting that dependency or updating the test to work with the new version will do it.

**Comment by azbarroso** [comment]
Hi @chatch thanks for the quick reply! I'm getting this error below when trying to do a production build ("npm run build") on a windows box... Have you seen this error before? Might not be related to the latest changes, but please let me know if you have any clue on this. Thanks again!

Creating an optimized production build...
Failed to compile.
Failed to minify the code from this file:
        ./node_modules/parse5/lib/utils/mixin.js:3
Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! stellarexplorer@1.0.15 build: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the stellarexplorer@1.0.15 build script.

**Comment by chatch** [comment]
> Hi @chatch thanks for the quick reply! I'm getting this error below when trying to do a production build ("npm run build") on a windows box... Have you seen this error before? Might not be related to the latest changes, but please let me know if you have any clue on this. Thanks again!
> 
> Creating an optimized production build...
> Failed to compile.
> Failed to minify the code from this file:
> ./node_modules/parse5/lib/utils/mixin.js:3
> Read more here: http://bit.ly/2tRViJ9
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! stellarexplorer@1.0.15 build: `node scripts/build.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the stellarexplorer@1.0.15 build script.

No I havn't seen this before. It runs fine for me locally - on Linux though.

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
