### ISSUE TITLE
XLM NEVER RECEIVED 

### ISSUE THREAD

**Issue by ironmanrules81** [chatch/stellarexplorer#193]
###  Please NOTE the following before creating an issue:

* stellarexplorer ([steexp.com](https://steexp.com)) is a readonly view of the Stellar ledger so we can't help retrieve lost funds
* if your having trouble locating funds sent to an exchange (eg. Binance), contact the exchange directly
* if you entered an incorrect memo or forgot to enter your memo, we unfortunately can't help. contact the recipient and tell them your sending address

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

## Issue Description

I HAD WITHDRAWN XLM FROM NEXO WALLET WITH MEMO_TXT INSTEAD OF MEMO_ID.  MY TRANSACTION DOES NOT EVEN SHOW UP ON THE BLOCKCHAIN.

**Comment by ironmanrules81** [comment]
![Screenshot_20210129-090907_ProtonMail](https://user-images.githubusercontent.com/78217608/106285545-ada5d280-6255-11eb-82c3-5fba1fa95980.jpg)

This was the transaction from nexo to my cex.io wallet.  Where is my funds?

**Comment by ironmanrules81** [comment]
This is the wallet address I sent from
![Uploading Screenshot_20210129-171731_Nexo Wallet.jpg…]()

**Comment by ironmanrules81** [comment]
![Screenshot_20210129-171731_Nexo Wallet](https://user-images.githubusercontent.com/78217608/106286136-5e13d680-6256-11eb-898e-982c0d3202c2.jpg)

This is the wallet it was sent from

**Comment by ironmanrules81** [comment]
![Screenshot_20210129-172334_Nexo Wallet](https://user-images.githubusercontent.com/78217608/106286497-c498f480-6256-11eb-9874-2b3858e78040.jpg)

It appears the balance is there when I clicked the wallet address.  Please change from memo_txt to memo_id and forward my tokens.

**Comment by hussinnasan** [comment]
Hi I have send XLM from my Coinbase wallet to Binance but I didn't receive any in Binance 
Any help can you please thank you

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
