### ISSUE TITLE
Hi I have send XLM from my Coinbase wallet to Binance but I didn't receive any in Binance

### ISSUE THREAD

**Issue by hussinnasan** [chatch/stellarexplorer#194]
Hi I have send XLM from my Coinbase wallet to Binance but I didn't receive any in Binance 
Any help can you please thank you 

__Originally posted by @hussinnasan in https://github.com/chatch/stellarexplorer/issues/193#issuecomment-770582619__

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
