### ISSUE TITLE
Mr Lukasz

### ISSUE THREAD

**Issue by Lukaszzzz2015** [chatch/stellarexplorer#195]
Hi Iv send XLM stellar today from coinbase wallet to coinbase but never arrive. Iv send without memo. 3,139.0775565 XLM.

HASH : 2bcd40eefd00c184c9f19cc9d815002d10fe1ba5aa697f713ad00667c14490be

PAYMENT WENT TO: GDQP2KPQGKIHYJGXNUIYOMHARUARCA7DJT5F02FF00KY3B2WSQHG4W37

TRANSACTION NUMBER: 235AE2B8E45D080BA69487E52135B48593645A53E400B7CB44A4675F9CFFED64

LEDGER: 33801817 

Please someone help me 
Lukasz Kowalski

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
