### ISSUE TITLE
Hi I have send XLM to Binance from my Coinbase wallet and didn’t receive it

### ISSUE THREAD

**Issue by hussinnasan** [chatch/stellarexplorer#196]
ACCOUNTJSON
Public Key:
GCL5UC4CUSSSJ4YUY45FHMXEXKK5JXTAKT26DJUXZBPWQDJ44FE434Z6
Home Domain:
Subentry Count:
0
TRANSACTION D1AD8761999E12B5D56FB37E8806069428DF0052D249C849B3F01A20F563AE2CJSON
Time	01/02/2021 04:24
Fee	stroops
Ledger	33797950
Memo (None)	

	Pay 3108.6945187 XLM to Binance	20 hours ago
Thank you

**Comment by tevhok** [comment]
I have made a transaction from one purse to another and I forgot to put the nemo, and the money does not reach the other purse, how can I get it back? thanks

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
