### ISSUE TITLE
Unrecognized operation causes nothing to render

### ISSUE THREAD

**Issue by leighmcculloch** [chatch/stellarexplorer#197]
## Issue Description

It appears that when steexp.com is pointed to a Horizon that has experimental or unrecognized operations on it, the website errors. I saw this happen when I had it pointed to a testing instance of Horizon that has a new operation that is not yet released deployed to it.

This is a screenshot of what I see in this case:
<img width="1342" alt="Screen Shot 2021-02-01 at 7 56 04 PM" src="https://user-images.githubusercontent.com/351529/106550205-8ce4b380-64c7-11eb-8e0b-5aa7028c36f0.png">

Most of steexp.com is very resilient to new fields, flags, and options, and I noticed when I was experimenting with new account flags on a Horizon test instance that steexp.com even displayed those flags. It would be very useful if when the website sees an operation it is unfamiliar, that it display some general generic information about the operation using the name/type available in the Horizon JSON.

**Comment by leighmcculloch** [comment]
I think if there was a fallback operation defined here that would probably mean an unrecognized operation could be displayed in a general way:
https://github.com/chatch/stellarexplorer/blob/32ed0b7f92c37d2a87233d9c0127671fb4be9df1/src/components/operations/Operation.js#L22-L51

**Comment by leighmcculloch** [comment]
I opened #198 that displays a simple message for unrecognized operation that includes the operation type.

**Comment by chatch** [comment]
thank you @leighmcculloch. even added the translations!

i'll take a look at what that new operation is too and prepare for it sometime.

**Comment by chatch** [comment]
oh also, could you post the testnet URL that caused the failure? if you still have this. thanks.
