### ISSUE TITLE
Sent Xlm but not credited

### ISSUE THREAD

**Issue by imsurajy** [chatch/stellarexplorer#199]
I have sent xlm from binance to WazirX but not credited yet. My Receiving address is - GA6SXIZIKLJHCZI2KEOBEUUOFMM4JUPPM2UTWX6STAWT25JWIEUFIMFF
Memo - 7030408245
Plz solve this issue asap.

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
