### ISSUE TITLE
Transfer never credited 

### ISSUE THREAD

**Issue by jmills31** [chatch/stellarexplorer#200]
I transferred xlm credits from Coinbase wallet to Coinbase and was never credited. The number is GDQP2KPQGKIHYJGXNUIYOMHARUARCA7DJT5FO2FFOOKY3B2WSQHG4W37

**Comment by yuenkwai** [comment]
Did you ever get your transfer to Coinbase? I sent xlm to them also , it has been six days and still nothing.

**Comment by jmills31** [comment]
No I haven’t

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
