### ISSUE TITLE
Transaction

### ISSUE THREAD

**Issue by bakulgabah** [chatch/stellarexplorer#208]
I made a transaction the address and memo are correct. . But my money has not been sent
What should I do.?
I want my money back.

**Comment by bakulgabah** [comment]
GC4KAS6W2YCGJGLP633A6F6AKTCV4WSLMTMIQRSEQE5QRRVKSX7THV6S

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
