### ISSUE TITLE
Wrong Withdrawal Address 

### ISSUE THREAD

**Issue by CCammock** [chatch/stellarexplorer#209]
Good afternoon; I'm reaching out to you as I try to receive my stellar Luman coin. This morning I attempted to transfer my funds; however, one letter was wrong, leaving my coin lost in the blockchain. My coin base wallet is GDQP2KPQGKIHYJGXNUIYOMHARUARCA7DJT5FO2FFOOKY3B2WSQHG4W37
with a memo of 1587756594

Please help these funds make it to my account; Below, you will find the address I attempted to send it to; if you can please place my funds into my coin base wallet, it would be much appreciated.

GDQP2KPQGQIHYJGXNUIYOMHARUARCA7DJT5FO2FFOOKY3B2WSQHG4W37
Memo 1587756594
XLM Funds tried transferring 294.6269906 
Date: 2021-02-08 11:22:14

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
