### ISSUE TITLE
Is NEXO a scammer? 

### ISSUE THREAD

**Issue by Tanathad25** [chatch/stellarexplorer#210]
I have transferred my XLM transaction to them, but no coin into my wallet.
Is NEXO a scammer?

**Comment by chatch** [comment]
don't appear to be. see trade volumes, ranking, etc. on cmc: https://coinmarketcap.com/currencies/nexo/

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
