### ISSUE TITLE
XLM never came through 

### ISSUE THREAD

**Issue by pcerullo1990** [chatch/stellarexplorer#211]
Hello,

I sent XLM from Nexo wallet to Coinbase over a week ago. It shows "approved". The XLM is no longer in my Nexo wallet and it is not in my Coinbase as well. 

Can someone please help me to find this money. Coinbase cannot assist.

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
