### ISSUE TITLE
Wrong memo, right address

### ISSUE THREAD

**Issue by ErikKomac** [chatch/stellarexplorer#212]
Hello,
I send 762 XLM to right address, but wrong memo.

I attached file with both transactions. The upper transaction (762 XLM) has
wrong memo. The lower transaction has correct memo and was send correctly.

Can you help me?

The receiver is also registered on BINANCE. His name is Tomaž Prebil and he is from
Slovenija.

Thank you.

Best regards, Erik Komac 
[XLM-wrong memo.docx](https://github.com/chatch/stellarexplorer/files/5974813/XLM-wrong.memo.docx)

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
