### ISSUE TITLE
Wrong Memo

### ISSUE THREAD

**Issue by Norbite** [chatch/stellarexplorer#214]
Hello
I sent 376,39 XLM to right address,but wrong memo

I sent it from Binance to my Wirex account.

Can You help me ?
Thank You!
![image](https://user-images.githubusercontent.com/78996160/107843206-6f69f080-6dc9-11eb-9f05-03fa1f9c13b0.png)

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
