### ISSUE TITLE
Wrong memo

### ISSUE THREAD

**Issue by chautran92** [chatch/stellarexplorer#215]
Please kindly see the attached. I scanned the QR code but somehow the memo was entered incorrectly so the recipient hasn’t received the fund yet. Thank you!

correct address GAHK7EEG2WWHVKDNT4CEQFZGKF2LGDSW2IVM4S5DP42RBW3K6BTODB4A 

Correct memo: 1084222359

quantity 24.7652 XLM
![43F8445F-85E3-4D0F-A13D-680A891DA326](https://user-images.githubusercontent.com/78996941/107843017-301dae80-6d8d-11eb-9cd2-ada68b1cc75a.png)
 
###  Please NOTE the following before creating an issue:

* stellarexplorer ([steexp.com](https://steexp.com)) is a readonly view of the Stellar ledger so we can't help retrieve lost funds
* if your having trouble locating funds sent to an exchange (eg. Binance), contact the exchange directly
* if you entered an incorrect memo or forgot to enter your memo, we unfortunately can't help. contact the recipient and tell them your sending address

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

**Comment by Wint-Bi** [comment]
I had a similar issue as well. However, binance.US has not response anything. Is that mean I lost all my XLM? The correct address but incorrect memo. Any idea how can I get back my XLM? Much appreciated

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
