### ISSUE TITLE
Wrong MEMO- Binance to Binance.US 

### ISSUE THREAD

**Issue by Neto8412** [chatch/stellarexplorer#217]
While trying to transfer my XLM from my Binance to my new Binance.US account I didn’t put in the correct MEMO which should have been 1040299952. I accidentally typed in XLM.

The TXID is-34FFDA72C7E24526E0C667881267117C729EF04725708127191DE0B6F66EA006

The deposit wallet that the XLM needs to go to is GBUTD5DNV43JBJP7AA657H2CYPUCAAFBXCKX7QE4XXGYIYFZZX2EKKVF 

please help! 

###  Please NOTE the following before creating an issue:

* stellarexplorer ([steexp.com](https://steexp.com)) is a readonly view of the Stellar ledger so we can't help retrieve lost funds
* if your having trouble locating funds sent to an exchange (eg. Binance), contact the exchange directly
* if you entered an incorrect memo or forgot to enter your memo, we unfortunately can't help. contact the recipient and tell them your sending address

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
