### ISSUE TITLE
Xlm not receve

### ISSUE THREAD

**Issue by sidisco** [chatch/stellarexplorer#220]
Hello,

I sent XLM from my Coinbase wallet to Coinbase over 2 Das ago. It shows "approved". The XLM is no longer in my Coinbase wallet and it is not in my Coinbase as well.

Can someone please help me to find this money. Coinbase cannot assist.

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
