### ISSUE TITLE
Envío a otra cuenta

### ISSUE THREAD

**Issue by oneka8** [chatch/stellarexplorer#221]
Buenas, envié unas monedas a otra cartera de mi propiedad en otra aplicación y parece ser que se me olvidó poner algún dato y no me ha llegado, la transacción fue la número: 62a70412d1d84de0c43a5ad0c9dcd6a03822122baf44cbb363317bb6f3f8acd5.
Espero que se pueda solucionar.

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
