### ISSUE TITLE
XLM withdrawal from Nexo.io never went through

### ISSUE THREAD

**Issue by timothykee** [chatch/stellarexplorer#224]
Transaction id
4a86ab60353c6eac83169df8bea7fe6ba6f515590066986f7510835e2f47bf8d

I withdraw 8000 xlm from nexo wallet android app to binance,  affirm correct recipient address and memo,  but it never reach binance.
Please help find out for me what went wrong and how to correct.  NEXO tech support has kept me waiting since Jan 29 with no progress.
Thanks in advance.

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
