### ISSUE TITLE
wrong memo i have send XLM from Binance to Coinbase

### ISSUE THREAD

**Issue by jonikurd** [chatch/stellarexplorer#225]
Send xlm from binance to coinbase

Adresse GDQP2KPQGKIHYJGXNUIYOMHARUARCA7DJT5FO2FFOOKY3B2WSQHG4W37

correct Memo 3410298118

Wrong Memo HYJGX

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
