### ISSUE TITLE
lost coins

### ISSUE THREAD

**Issue by Nismo143** [chatch/stellarexplorer#226]
###  Please NOTE the following before creating an issue:

* stellarexplorer ([steexp.com](https://steexp.com)) is a readonly view of the Stellar ledger so we can't help retrieve lost funds
* if your having trouble locating funds sent to an exchange (eg. Binance), contact the exchange directly
* if you entered an incorrect memo or forgot to enter your memo, we unfortunately can't help. contact the recipient and tell them your sending address

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

## Issue Description Lost coins
i sent xlm from binance to coinbase and its cleared on binance but stil not recivived in coinbase need help thank you.
![Screenshot (6)](https://user-images.githubusercontent.com/37425776/108638382-9ae97c80-7454-11eb-8b38-857df4ff1275.png)

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
