### ISSUE TITLE
I sent stellar from binance to my atomic wallet but still didnt recieve it the txid: 4f8cdc847ac9eabb8756285bd8bba76404cf3a4559048d5abb55c1ac7a806dd1

### ISSUE THREAD

**Issue by mohamadrezmadani7856** [chatch/stellarexplorer#227]
###  Please NOTE the following before creating an issue:

* stellarexplorer ([steexp.com](https://steexp.com)) is a readonly view of the Stellar ledger so we can't help retrieve lost funds
* if your having trouble locating funds sent to an exchange (eg. Binance), contact the exchange directly
* if you entered an incorrect memo or forgot to enter your memo, we unfortunately can't help. contact the recipient and tell them your sending address

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

**Comment by Mendez849** [comment]
Hello Mate, Sorry to hear about your issue, you can contact Atomic Wallet Support on Telegram via the weblink www.t.me/theatomicwallet They'll be happy to resolve your issue. Cheers.

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
