### ISSUE TITLE
Missing Deposit

### ISSUE THREAD

**Issue by sw5001** [chatch/stellarexplorer#228]
{
  "_links": {
    "self": {
      "href": "https://horizon.stellar.org/operations/146437352339353601"
    },
    "transaction": {
      "href": "https://horizon.stellar.org/transactions/617e34d46186e2c554fba173f00639a9dc08e6c6bdc0e4ad7fd87dad73a23fcf"
    },
    "effects": {
      "href": "https://horizon.stellar.org/operations/146437352339353601/effects"
    },
    "succeeds": {
      "href": "https://horizon.stellar.org/effects?order=desc\u0026cursor=146437352339353601"
    },
    "precedes": {
      "href": "https://horizon.stellar.org/effects?order=asc\u0026cursor=146437352339353601"
    }
  },
  "id": "146437352339353601",
  "paging_token": "146437352339353601",
  "transaction_successful": true,
  I sent from my wallet to Coinbase. It hasn’t been received yet. 
  

"source_account": "GCS6P3FZDOL3WHC4U62TJKX37TV5AAEXL52BJVAFVDVZLKH2JMC6ZQ73",
  "type": "payment",
  "type_i": 1,
  "created_at": "2021-02-21T01:33:26Z",
  "transaction_hash": "617e34d46186e2c554fba173f00639a9dc08e6c6bdc0e4ad7fd87dad73a23fcf",
  "asset_type": "native",
  "from": "GCS6P3FZDOL3WHC4U62TJKX37TV5AAEXL52BJVAFVDVZLKH2JMC6ZQ73",
  "to": "GDQP2KPQGKIHYJGXNUIYOMHARUARCA7DJT5FO2FFOOKY3B2WSQHG4W37",
  "amount": "204.5253333"
}

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
