### ISSUE TITLE
No memo 

### ISSUE THREAD

**Issue by Mrawesome1898** [chatch/stellarexplorer#229]
###  Please NOTE the following before creating an issue:

* stellarexplorer ([steexp.com](https://steexp.com)) is a readonly view of the Stellar ledger so we can't help retrieve lost funds
* if your having trouble locating funds sent to an exchange (eg. Binance), contact the exchange directly
* if you entered an incorrect memo or forgot to enter your memo, we unfortunately can't help. contact the recipient and tell them your sending address

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

## Issue Description
I sent XLM from my Coinbase to my free wallet (both my own accounts) without a memo how can I fix it GAN5X2FUP2PCQITFAZE2CB5PBTGVZKVJLUDVTRRRV7PTZYQWYD4CRP65

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this

**Comment by Mrawesome1898** [comment]
I am the recipient I was moving it from one wallet to another. So it’s just
gone?

**Comment by chatch** [comment]
i don't know because it's coinbase. you'll have to ask coinbase. this software simply allows viewing of the transactions on the ledger and can't see what coinbase does with transactions with or without memos ...

**Comment by chatch** [comment]
have you asked coinbase?

**Comment by Mrawesome1898** [comment]
I but I will first thing I just saw this email. Thanks I will let you know
what I find out

**Comment by Mrawesome1898** [comment]
You asked what Coinbase said about my missing transaction and here is the
response
---------- Forwarded message ---------
From: Coinbase Support ***@***.***>
Date: Mon, Apr 12, 2021 at 2:19 PM
Subject: [Reply] Case #05227825 - Stellar lumen memo
To: ***@***.*** ***@***.***>


Hello Marvin,

Thank you for contacting Coinbase Support.

According to our records, the funds you asked about were successfully sent
out of your account. You can view confirmation of the transaction here:
https://stellar.expert/explorer/public/tx/f95adfae566eef0e0fea63e2374378a1662161f5e71250fe94bd64e7ec07d501

A couple things to note when viewing the transaction confirmation:
1. Coinbase is a hosted wallet service and batches transactions for
blockchain efficiency to provide cheaper network fees for customers
2. The transaction hash may include multiple transactions, which is why you
may see several addresses, including the address associated with your send
3. If you're looking for your own wallet address, please press the
"Receive" button in your Coinbase account.

What you can do next:
- If the external address you sent to is one you own, you can reach out to
that wallet’s support team for further assistance
- If you intended to send these funds to another party, please use the link
above as conclusive proof that your funds were successfully sent to that
address
- You can contact the recipient to see if they are able to refund your
transaction
- If you do need a refund, make sure you provide the receiving party with
the transaction hash/id and one of your wallet addresses to send the refund
to
- Do not send the funds directly back to the Coinbase address they came
from. You can find your specific Coinbase deposit addresses for each wallet
here: https://www.coinbase.com/addresses.

Cryptocurrency transactions are irreversible and funds cannot be canceled,
reversed, or recovered by Coinbase once they have been sent out of your
account.

Please note, if a transaction has a transaction hash, the funds have been
sent on the blockchain. However, Coinbase does not consider a transaction
“complete” until it reaches a certain amount of confirmations, seen here:
https://help.coinbase.com/en/coinbase/trading-and-funding/sending-or-receiving-cryptocurrency/why-is-my-transaction-pending

Thanks,

Coinbase Support

ref:_00D6A2G0qc._5003sSCCMe:ref
