### ISSUE TITLE
Sent from binance to coinbase not found

### ISSUE THREAD

**Issue by yes200** [chatch/stellarexplorer#230]
###  Please NOTE the following before creating an issue:

ACC : GDQP2KPQGKIHYJGXNUIYOMHARUARCA7DJT5FO2FFOOKY3B2WSQHG4W37

Memo: 957893127

Transaction Id: 6e047e8836e10ef67bb2b35e418658bcd347ec3e2717603948d48df05e2cb

6e047e8836e10ef67bb2b35e418658bcd347ec3e2717603948d48df05e2cb6de

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this

**Comment by yes200** [comment]
Thank you
