### ISSUE TITLE
Не получены средства

### ISSUE THREAD

**Issue by aahilko** [chatch/stellarexplorer#232]
Здравствуйте. До сих пор средства не поступили. Транзакция: 3575ef813f9df932706eb5c24ffb2d83a12a50f12a1c89c85bb5915009020fa4
На счет Coinbase GDQP2KPQGKIHYJGXNUIYOMHARUARCA7DJT5FO2FFOOKY3B2WSQHG4W37

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
