### ISSUE TITLE
Coinbase said they haven't received funds 

### ISSUE THREAD

**Issue by whatabarber** [chatch/stellarexplorer#233]
###  Please NOTE the following before creating an issue:

* stellarexplorer ([steexp.com](https://steexp.com)) is a readonly view of the Stellar ledger so we can't help retrieve lost funds
* if your having trouble locating funds sent to an exchange (eg. Binance), contact the exchange directly
* if you entered an incorrect memo or forgot to enter your memo, we unfortunately can't help. contact the recipient and tell them your sending address

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank yo
## Issue Description

Afternoon, i sent funds from Binance to coinbase and forgot memo. Of course you don’t help with that but Coinbase say they don’t have my funds. I’ve given them my 2 steexp.com transaction urls. Now this isn’t making sense to me if i sent the correct wallet , so now it’s like the money is missing. Coinbase said to hit Binance, now it’s just a big run around when i click on my steexp.com url n it says config.memo_required. I asking for any kind of help. Thank you

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
