### ISSUE TITLE
Не зачислены stellar на кошелек 

### ISSUE THREAD

**Issue by tyns362** [chatch/stellarexplorer#237]
https://steexp.com/account/GAN5X2FUP2PCQITFAZE2CB5PBTGVZKVJLUDVTRRRV7PTZYQWYD4CRP65 
Посмотрите пожалуйста, уже неделю жду зачисление на кошелек freewallet, купил монеты, задавал вопросы в службу поддержки кошелька, нет определенного ответа! Спасибо!

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
