### ISSUE TITLE
Sponsorship and claimable balance operations and effects

### ISSUE THREAD

**Issue by leighmcculloch** [chatch/stellarexplorer#238]
## Issue Description

I've noticed when viewing accounts that have claimable balance operations, and sponsorship operations, that the generic 'unrecognized' operation text that was introduced in #198 gets displayed. I think this means the explorer doesn't currently have a definition for how to display these operations and so no meaningful information is being displayed.

The operations missing definitions appear to be:
- `create_claimable_balance`
- `claim_claimable_balance`
- `begin_sponsoring_future_reserves`
- `end_sponsoring_future_reserves`
- `revoke_sponsorship`

The list of operations are here:
https://github.com/stellar/go/blob/5c62e03/protocols/horizon/operations/main.go#L31-L35

Example:
<img width="1173" alt="Screen Shot 2021-03-03 at 1 21 17 PM" src="https://user-images.githubusercontent.com/351529/109873976-59f72200-7c23-11eb-9235-83ce9479af10.png">

Ref: https://steexp.com/account/GDTNXS4SNQFDXBVKOBU6QIAMAW6A3KV3VK4Z5RSDLAB7YXZSUIL2PU4X#operations

Similar with effects, there looks to be 18 effects missing definitions:
- `claimable_balance_created`
- `claimable_balance_claimed`
- `claimable_balance_claimant_created`
- `account_sponsorship_created`
- `account_sponsorship_updated`
- `account_sponsorship_removed`
- `trustline_sponsorship_created`
- `trustline_sponsorship_updated`
- `trustline_sponsorship_removed`
- `data_sponsorship_created`
- `data_sponsorship_updated`
- `data_sponsorship_removed`
- `claimable_balance_sponsorship_created`
- `claimable_balance_sponsorship_updated`
- `claimable_balance_sponsorship_removed`
- `signer_sponsorship_created`
- `signer_sponsorship_updated`
- `signer_sponsorship_removed`

The list of effects are here:
https://github.com/stellar/go/blob/5c62e03/protocols/horizon/effects/main.go#L207-L224

Example:
<img width="1173" alt="Screen Shot 2021-03-03 at 1 23 11 PM" src="https://user-images.githubusercontent.com/351529/109874178-9e82bd80-7c23-11eb-9031-2679edde8e56.png">

Ref: https://steexp.com/account/GDTNXS4SNQFDXBVKOBU6QIAMAW6A3KV3VK4Z5RSDLAB7YXZSUIL2PU4X#effects

**Comment by chatch** [comment]
Thank you @leighmcculloch . I'll look at adding support for these soon.

**Comment by ibur4tu** [comment]
at least it's not snplease help please check my transaction with txid 383e1098d5fce8fce6df9887f3041f4f06ea11a1a883e61603287d7ea1c534e2 it's been 24 hours and it hasn't arrived yet..
transaction confirmation stops at 30 confirmations..
Please helpowdog dao, yet..
