### ISSUE TITLE
XML missing. Tried to send from coinbase wallet to coinbase and inserted the memo correct? 

### ISSUE THREAD

**Issue by Kush212** [chatch/stellarexplorer#244]
###  Please NOTE the following before creating an issue:

* stellarexplorer ([steexp.com](https://steexp.com)) is a readonly view of the Stellar ledger so we can't help retrieve lost funds
* if your having trouble locating funds sent to an exchange (eg. Binance), contact the exchange directly
* if you entered an incorrect memo or forgot to enter your memo, we unfortunately can't help. contact the recipient and tell them your sending address

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

**Comment by pollux254** [comment]
Coinbase sucks! It isn’t my first time losing XLM. And it’s just xlm. I did xrp and others just fine. I think there is a glitch.

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this

**Comment by veryupset9** [comment]
I believe there is a glitch. This is bullshit. I have an invalid hash. And coinbase says this after I provided them the hash. So messed up

**Comment by Kush212** [comment]
No I forgot the (memo) that's why I lost the XLM
    On Sunday 5 December 2021, 03:10:51 GMT, veryupset9 ***@***.***> wrote:  
 
 


I believe there is a glitch. This is bullshit. I have an invalid hash. And coinbase says this after I provided them the hash. So messed up

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
