### ISSUE TITLE
40319D31CE51DA97FC8C97BE67F3FCCE783A879CE77343E2523F625D34854B1BJSON HOW CAN I MESSAGE THIS WALLET? MY XML WENT THERE AND IM TRYING TO RETRIVE IT. TIA

### ISSUE THREAD

**Issue by Kush212** [chatch/stellarexplorer#245]
###  Please NOTE the following before creating an issue:

* stellarexplorer ([steexp.com](https://steexp.com)) is a readonly view of the Stellar ledger so we can't help retrieve lost funds
* if your having trouble locating funds sent to an exchange (eg. Binance), contact the exchange directly
* if you entered an incorrect memo or forgot to enter your memo, we unfortunately can't help. contact the recipient and tell them your sending address

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this
