### ISSUE TITLE
My xlm didnt arrive

### ISSUE THREAD

**Issue by vio0103** [chatch/stellarexplorer#247]
Hi! I sent xlm from coinbase to my crypto account and didnt arrive...why? 
What can i do?

![BF78405D-D2BE-42CA-8D28-3215E97C66C8](https://user-images.githubusercontent.com/80538769/110972786-0ee8b780-8365-11eb-9ae6-ea835e12d195.png)

**Comment by chatch** [comment]
apologies, we can't help with issues like this as this software is just a READONLY view of the ledger. please contact the exchange or recipient to resolve issues like this

**Comment by chatch** [comment]
you'll need to ask coinbase. we can't help with this.

**Comment by veryupset9** [comment]
Bullshit they say ask you
