### ISSUE TITLE
transaction

### ISSUE THREAD

**Issue by BehzadGoudarzi** [chatch/stellarexplorer#252]
Hello Dear
Some XLM coin has been transferred to my wallet. But it was not transferred to my wallet due to not entering the MEMO field.
What exactly should I do?

**Comment by wallr1981** [comment]
This is my xlm

**Comment by wallr1981** [comment]
My xlm went to your wallet and I don't know why I put everything I was supposed to.

**Comment by wallr1981** [comment]
This happened to me too what do I need to do

**Comment by wallr1981** [comment]
The same thing happened to me what should I do

**Comment by wallr1981** [comment]
Have you had any luck

**Comment by fatihfatih0** [comment]
This happened to me too what do I need to do

**Comment by wallr1981** [comment]
You have to get the link to the transaction ID and send it to the exchange
for where it was being sent.
