### ISSUE TITLE
My transaction never transferred to my other exchange and everything is correct with address. What do I do?

### ISSUE THREAD

**Issue by deevvviin** [chatch/stellarexplorer#253]
###  Please NOTE the following before creating an issue:

WE CAN'T HELP WITH FUNDS NOT RECEIVED, DELAYED OR WRONG MEMOS - CONTACT THE EXCHANGE OR THE RECEIPIENT IN THESE CASES - Stellar Explorer IS JUST A READ ONLY VIEW OF THE LEDGER

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

**Comment by chatch** [comment]
talk to the exchange

**Comment by ozcanoff** [comment]
Merhabalar. Binance Cüzdanımdan, Bitfinex cüzdanıma dün akşam st: 22:50 de XLM çekimi yaptım. Fakat işlemim hala gerçekleşmedi. Kontrol ettiğimde Cüzdan adresimi ve memo adresimi doğru girdiğimi görüyorum. Konuyla ilgili yardımcı olun lütfen. 
Kanıt olarak yaptığım işlemin ve Cüzdan adresimin ekran görüntüsünü bırakıyorum.

![Ekran görüntüsü 2021-04-11 102505](https://user-images.githubusercontent.com/82309140/114297081-4ad38180-9ab7-11eb-8ff6-7852011c3d85.png)
![Ekran görüntüsü 2021-04-11 104028](https://user-images.githubusercontent.com/82309140/114297086-4f983580-9ab7-11eb-8a5a-f69458a891f8.png)
