### ISSUE TITLE
Never got my deposit I sent 

### ISSUE THREAD

**Issue by Purpletulips17** [chatch/stellarexplorer#255]
###  Please NOTE the following before creating an issue:
I never got my deposit and the Comoany Hotbit or Coinbase won’t reply . I have confirmed it was sent and they are both my accounts . Someone is about to be Suspended is all I know 

WE CAN'T HELP WITH FUNDS NOT RECEIVED, DELAYED OR WRONG MEMOS - CONTACT THE EXCHANGE OR THE RECEIPIENT IN THESE CASES - Stellar Explorer IS JUST A READ ONLY VIEW OF THE LEDGER

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

**Comment by Purpletulips17** [comment]
I sent money to Hotbit from Coinbase and both my accounts and it never received . Who stole the $ how do I get it back. This will not look good for future of crypto if we have verification we send stuff and it can get lost with no way to get back

**Comment by yamazaki779** [comment]
Same here, I lost my XLM from coinbase wallet.
