### ISSUE TITLE
Please refund my XLM. They never reached their destination 

### ISSUE THREAD

**Issue by AY20005** [chatch/stellarexplorer#261]
###  Please NOTE the following before creating an issue:

WE CAN'T HELP WITH FUNDS NOT RECEIVED, DELAYED OR WRONG MEMOS - CONTACT THE EXCHANGE OR THE RECEIPIENT IN THESE CASES - Stellar Explorer IS JUST A READ ONLY VIEW OF THE LEDGER

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

**Comment by Michaelorj** [comment]
> I deposited 68xlm to this wallet 
> From my trust wallet but I make mistake I used steller networ instead of BEF20 net work pls help me refund my xlm
> 

Dear investor,
having some issues in your trust wallet? Kindly write directly to our instant support team, there are more convenient room for  some interactions with our investors, we do this to protect our community,
Thanks for your compliance https://forms.gle/FqwRxhN2bDF5UVBw8
