### ISSUE TITLE
Missing memo on XLM

### ISSUE THREAD

**Issue by SarahBFulton** [chatch/stellarexplorer#267]
Sent XLM to Binance.us for some reason memo disappeared and I never received

ID 10015c3f-1e5d-2957-b55b-77ec6faf496e

TxID
8305bef5a1ea448d2de8806b903e6e1d2d801a91366d6a35e453d9a7e3826d8f

Ledger | 35121934

my XLM wallet codes

Address
GBUTD5DNV43JBJP7AA657H2CYPUCAAFBXCKX7QE4XXGYIYFZZX2EKKVF

Memo
1060978561

If you cannot correct and add memo please return to my original account

**Comment by jlynjim** [comment]
left wrong transaction code s/b

ID 10015c3f-1e5d-2957-b55b-77ec6faf496e

TxID 
8305bef5a1ea448d2de8806b903e6e1d2d801a91366d6a35e453d9a7e3826d8f

Ledger | 35121934

Info above is my XLM wallet codes
