### ISSUE TITLE
never got  my xlm from my coinbase wallet transfer

### ISSUE THREAD

**Issue by yamazaki779** [chatch/stellarexplorer#268]
![image](https://user-images.githubusercontent.com/83479827/116762987-cbfca500-a9e1-11eb-80fe-9fba16cb3571.jpeg)

**Comment by yamazaki779** [comment]
{
  "_links": {
    "self": {
      "href": "https://horizon.stellar.org/transactions/f20926da12d548bf8b9a94d5de71d9a83cf1cb3040f8c25ac4a39d55f001543f"
    },
    "account": {
      "href": "https://horizon.stellar.org/accounts/GD3RJYM7WNSVHBT53W2PVKJ3ZETOEK4LRZN3C4BC35GMVNMLF2ZNYRDQ"
    },
    "ledger": {
      "href": "https://horizon.stellar.org/ledgers/35012799"
    },
    "operations": {
      "href": "https://horizon.stellar.org/transactions/f20926da12d548bf8b9a94d5de71d9a83cf1cb3040f8c25ac4a39d55f001543f/operations{?cursor,limit,order}",
      "templated": true
    },
    "effects": {
      "href": "https://horizon.stellar.org/transactions/f20926da12d548bf8b9a94d5de71d9a83cf1cb3040f8c25ac4a39d55f001543f/effects{?cursor,limit,order}",
      "templated": true
    },
    "precedes": {
      "href": "https://horizon.stellar.org/transactions?order=asc\u0026cursor=150378826646724608"
    },
    "succeeds": {
      "href": "https://horizon.stellar.org/transactions?order=desc\u0026cursor=150378826646724608"
    },
    "transaction": {
      "href": "https://horizon.stellar.org/transactions/f20926da12d548bf8b9a94d5de71d9a83cf1cb3040f8c25ac4a39d55f001543f"
    }
  },
  "id": "f20926da12d548bf8b9a94d5de71d9a83cf1cb3040f8c25ac4a39d55f001543f",
  "paging_token": "150378826646724608",
  "successful": true,
  "hash": "f20926da12d548bf8b9a94d5de71d9a83cf1cb3040f8c25ac4a39d55f001543f",
  "ledger": 35012799,
  "created_at": "2021-04-20T02:29:28Z",
  "source_account": "GD3RJYM7WNSVHBT53W2PVKJ3ZETOEK4LRZN3C4BC35GMVNMLF2ZNYRDQ",
  "source_account_sequence": "150291119119269889",
  "fee_account": "GD3RJYM7WNSVHBT53W2PVKJ3ZETOEK4LRZN3C4BC35GMVNMLF2ZNYRDQ",
  "fee_charged": "100",
  "max_fee": "100",
  "operation_count": 1,
  "envelope_xdr": "AAAAAgAAAAD3FOGfs2VThn3dtPqpO8km4iuLjluxcCLfTMq1iy6y3AAAAGQCFfD6AAAAAQAAAAEAAAAAAAAAAAAAAABgfjzBAAAAAAAAAAEAAAAAAAAAAQAAAADg/SnwMpB8JNdtEYcw4I0BEQPjTPpXaKVzlY2HVpQObgAAAAAAAAAAx3f6TQAAAAAAAAABiy6y3AAAAED/tNJqW22plWaQPSubvFOjE9usimn0zNcUEShnljlZSCxXk78mCcnMDO0cBOsNm2RSzNRC5035L4r1Lr/svh4B",
  "result_xdr": "AAAAAAAAAGQAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAA=",
  "result_meta_xdr": "AAAAAgAAAAIAAAADAhZAvwAAAAAAAAAA9xThn7NlU4Z93bT6qTvJJuIri45bsXAi30zKtYsustwAAAAAyBCQzQIV8PoAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAABAhZAvwAAAAAAAAAA9xThn7NlU4Z93bT6qTvJJuIri45bsXAi30zKtYsustwAAAAAyBCQzQIV8PoAAAABAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAABAAAABAAAAAMCFkC/AAAAAAAAAADg/SnwMpB8JNdtEYcw4I0BEQPjTPpXaKVzlY2HVpQObgAAAFK241EpAVvmQAAHq30AAAABAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAECFkC/AAAAAAAAAADg/SnwMpB8JNdtEYcw4I0BEQPjTPpXaKVzlY2HVpQObgAAAFN+W0t2AVvmQAAHq30AAAABAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAMCFkC/AAAAAAAAAAD3FOGfs2VThn3dtPqpO8km4iuLjluxcCLfTMq1iy6y3AAAAADIEJDNAhXw+gAAAAEAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAECFkC/AAAAAAAAAAD3FOGfs2VThn3dtPqpO8km4iuLjluxcCLfTMq1iy6y3AAAAAAAmJaAAhXw+gAAAAEAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAA=",
  "fee_meta_xdr": "AAAAAgAAAAMCFfD6AAAAAAAAAAD3FOGfs2VThn3dtPqpO8km4iuLjluxcCLfTMq1iy6y3AAAAADIEJExAhXw+gAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAECFkC/AAAAAAAAAAD3FOGfs2VThn3dtPqpO8km4iuLjluxcCLfTMq1iy6y3AAAAADIEJDNAhXw+gAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAA==",
  "memo_type": "none",
  "signatures": [
    "/7TSalttqZVmkD0rm7xToxPbrIpp9MzXFBEoZ5Y5WUgsV5O/JgnJzAztHATrDZtkUszUQudN+S+K9S6/7L4eAQ=="
  ],
  "valid_after": "1970-01-01T00:00:00Z",
  "valid_before": "2021-04-20T02:30:25Z"
}

**Comment by yamazaki779** [comment]
It's totally lost

**Comment by Jessicadrichardson** [comment]
I had something similar happen.

**Comment by tanitt** [comment]
Me too what should i do

**Comment by yamazaki779** [comment]
> Me too what should i do
I have no idea, but I would never use coinbase wallet again☹️

**Comment by cmyers1217** [comment]
> Me too what should i do

**Comment by dannygsan** [comment]
Same problem here!

**Comment by chatch** [comment]
was this to coinbase or from coinbase? if it's to, can't you contact coinbase support?

**Comment by yamazaki779** [comment]
> was this to coinbase or from coinbase? if it's to, can't you contact coinbase support?

Yes , my this transaction was no memo, that's why got lost .  I am trying to do contact coinbase and filed the request help, just let's see how it work. I hope they can help me.

**Comment by dannygsan** [comment]
Already contacted coinbase support. Waiting on an answer. In my case i transfered from the coinbase wallet to the regular coinbase trading aaaand it's gone 😅
