### ISSUE TITLE
Ya arkadas Memo adresin yanlış diye xlm yatmadı iptal edin onu ya

### ISSUE THREAD

**Issue by celalet** [chatch/stellarexplorer#270]
![Screenshot_2021-05-08-16-50-56-798_com mi globalbrowser](https://user-images.githubusercontent.com/83166147/117555169-8edd8600-b065-11eb-9c82-86c9464e5f67.jpg)

Txhash ;
badf6cc761bfb53f421cec59c6c91a0628aa830b4b2b4b110436b150d2a94798

Pls help me

**Comment by celalet** [comment]
İptal edin bu işlemi mi

**Comment by chatch** [comment]
contact the receiver. is it an exchnage?
