### ISSUE TITLE
The withdrawal order was successful, but the money did not enter.

### ISSUE THREAD

**Issue by phamphat-pleum** [chatch/stellarexplorer#273]
The withdrawal order was successful, but the money did not enter. From bitkub to gate.io XLM Coin please check for me.

- [ ] 

- [ ] 
![Screenshot_20210511-100504_Gmail](https://user-images.githubusercontent.com/83997121/117752111-6bbafe00-b240-11eb-9d02-480244796185.jpg)
![Screenshot_20210511-100113_Samsung Internet](https://user-images.githubusercontent.com/83997121/117752130-737aa280-b240-11eb-9ae2-5e7e7b8e3de7.jpg)
![Screenshot_20210511-093543_gateio](https://user-images.githubusercontent.com/83997121/117752134-74abcf80-b240-11eb-9fda-457e810e8963.jpg)

**Comment by thaenalpha** [comment]
> 
> 
> The withdrawal order was successful, but the money did not enter. From bitkub to gate.io XLM Coin please check for me.
> 
>  
I have got the same problem, please help

**Comment by yodsapo** [comment]
![Uploading Screenshot_20210511-102540_Chrome.jpg…]()

**Comment by momonono16** [comment]
> ผมก็เจอปัญหานี้เช่นกันครับถอนxlmจากbitkubไปbitmart แต่รายการทำธุรกรรมฟ้องว่าerror ครับ
> ![Screenshot_20210511-123750_Gmail](https://user-images.githubusercontent.com/84002227/117764064-17bb1400-b256-11eb-882d-504d0e906a75.jpg)
> ![Screenshot_20210511-123810_Gmail](https://user-images.githubusercontent.com/84002227/117764073-1a1d6e00-b256-11eb-900c-0709854506c2.jpg)
> ![Screenshot_20210511-123721_BitMart](https://user-images.githubusercontent.com/84002227/117764079-1be73180-b256-11eb-9252-6f4a986d3a39.jpg)

ตอนนี้เหรียญเข้ายังครับผมก็เป็นเหมือนกัน

**Comment by thaenalpha** [comment]
> > ของผมเข้าแล้วนะครับ
> 
> นานไหมครับ

7 ชม.ได้ครับ

**Comment by natty123456** [comment]
ของเราได้ทำการโอนเหรียญ Six  ผ่านเว็บไซด์ Definix แต่ได้ทำการเปลี่ยนเครือข่ายแล้วเป็น stellar ไป  binance smart chain เพื่อเข้ากระเป๋า Metamask ทำการเช็ค ticket id ก็ไม่ได้ เพราะขึ้น error แบบนี้ต้องติดต่อ support ที่ไหนคะ

**Comment by thaenalpha** [comment]
> 
> 
> ของเราได้ทำการโอนเหรียญ Six ผ่านเว็บไซด์ Definix แต่ได้ทำการเปลี่ยนเครือข่ายแล้วเป็น stellar ไป binance smart chain เพื่อเข้ากระเป๋า Metamask ทำการเช็ค ticket id ก็ไม่ได้ เพราะขึ้น error แบบนี้ต้องติดต่อ support เว็บไวซ์ไหนคะ ทำการโอนตั้งแต่ 23.59 ป่านนี้เหรียญยังไม่เข้ากระเป๋า Metamask เลยค่ะ

Definix ครับ ถ้ากระเป๋าปลายทางเป็น Stellar ด้วยก็จะไม่มีปัญหานะครับ แต่ถ้าเป็น bsc ก็น่าจะทำเรื่องตามเหรียญคืน ลองดูนะครับ ขอให้ได้คืน
