### ISSUE TITLE
Total noob questions. 

### ISSUE THREAD

**Issue by anticgov** [chatch/stellarexplorer#274]
My original intent was to ask why my XLM didint make it to coinbase from my coinbase wallet. After reading the Note below I understand I won't be getting any help receiving my disappearing XLM. However would someone help me understand what I'm looking at and point me in the right direction on where to start looking for my          un-recieved XLM? I did email the coinbase wallet, currently I've got no response from them. Thanks and sorry for the noob questions.  

###  Please NOTE the following before creating an issue:

WE CAN'T HELP WITH FUNDS NOT RECEIVED, DELAYED OR WRONG MEMOS - CONTACT THE EXCHANGE OR THE RECEIPIENT IN THESE CASES - Stellar Explorer IS JUST A READ ONLY VIEW OF THE LEDGER

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

**Comment by chatch** [comment]
yes unfortunately it's in the receives hands, so coinbase is the only one can do something about this. hopefully they will reply to your request.

**Comment by ParkerBee77** [comment]
Why is it the send operation does not have function allowing check for address verification, memo approval, a freeze all funds/transactions for such events with errors or potential theft attempts to ensure transactions are proper?!

**Comment by chatch** [comment]
closing, not related to stellarexplorer
