### ISSUE TITLE
I don’t recived  xlm in my wallet. 

### ISSUE THREAD

**Issue by wuttisak2223** [chatch/stellarexplorer#275]
![6B4AB132-35AB-42C4-AFF0-73B7872561B3](https://user-images.githubusercontent.com/84001071/117760690-4b933b00-b250-11eb-91f8-fd0114ba0935.png)
###  Please NOTE the following before creating an issue:

WE CAN'T HELP WITH FUNDS NOT RECEIVED, DELAYED OR WRONG MEMOS - CONTACT THE EXCHANGE OR THE RECEIPIENT IN THESE CASES - Stellar Explorer IS JUST A READ ONLY VIEW OF THE LEDGER

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

**Comment by nat3962** [comment]
Coin เข้ารึยังครับ ตกลงต้องแจ้งเรื่องไปที่ใครครับ

**Comment by wuttisak2223** [comment]
ติดต่อsupport bitkub ได้ช่วงเย็น เหรียญเข้าเรียบร้อยครับ ขอบคุณมากครับ

เมื่อ อ. 11 พ.ค. 2564 เวลา 17:31 nat3962 ***@***.***>
เขียนว่า:
