### ISSUE TITLE
Don't receive xlm in Binance and Txn is not found

### ISSUE THREAD

**Issue by jackgurae** [chatch/stellarexplorer#283]
Send xlm from bitkub exchange. Receive confirmation from bitkub with txn. Correct address, correct memo, correct chain.

https://steexp.com/error/not-found/fc67a9b6a910a8e8707b587d74abc224492c42bae347c70e0a8de813a6d7ded2

It is not found.

###  Please NOTE the following before creating an issue:

WE CAN'T HELP WITH FUNDS NOT RECEIVED, DELAYED OR WRONG MEMOS - CONTACT THE EXCHANGE OR THE RECEIPIENT IN THESE CASES - Stellar Explorer IS JUST A READ ONLY VIEW OF THE LEDGER

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

**Comment by jackgurae** [comment]
![Screenshot_20210511-193846](https://user-images.githubusercontent.com/6565650/117817750-1c052280-b292-11eb-9fc1-7c0dcf750f70.jpg)

**Comment by compact2541** [comment]
ผมก็โดนครับ

**Comment by Mularn6789** [comment]
โดนเหมือนกันโอนตั้งแต่วันอาทิตย์ทาง Bitkub Confirm แล้วแต่เหรียญไม่เข้า Bitmart  จะตามได้ยังไงคะแนะนำหน่อยคะ

**Comment by momonono16** [comment]
ผมก็โดนเหมือนกันครับตอนนี้เหรียญเข้ายังครับ

**Comment by jackgurae** [comment]
เงินเข้าแล้วครับ ฝาก6โมง 10โมงเช้าอีกวันเพิ่งเข้า
คุยกับ support bitkub เค้าบอกว่าเค้าออก txid แล้ว แต่แค่มันยังไม่ถูก block มันเลยยัง not found ถ้าเชื่อ bitkub ก็คือปัญหาอยู่ที่ traffic xlm 
แต่จากที่ดูคนแจ้งกันปัญหากันในนี้ มีแต่คนไทย ผมว่า bitkub นั้นแหละมีปัญหา
