### ISSUE TITLE
XLM not recived.

### ISSUE THREAD

**Issue by nestor2011** [chatch/stellarexplorer#287]
###  Please NOTE the following before creating an issue:

WE CAN'T HELP WITH FUNDS NOT RECEIVED, DELAYED OR WRONG MEMOS - CONTACT THE EXCHANGE OR THE RECEIPIENT IN THESE CASES - Stellar Explorer IS JUST A READ ONLY VIEW OF THE LEDGER

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

**Comment by Demiradiyaman** [comment]
Ben hesebiniza para atım
Malesef transfer edemedim

**Comment by Demiradiyaman** [comment]
Ne yapmalıyım bana yardımcı olursanız sevinirim teşekkürler

**Comment by Demiradiyaman** [comment]
Gri. Aynı hesaba nasıl atacam
