### ISSUE TITLE
Indicate when the view is out of sync with the server

### ISSUE THREAD

**Issue by chatch** [chatch/stellarexplorer#29]
It would be nice to indicate the sync is happening whilst it's happing and to flag the data shown is stale.

Maybe a green light / red light sitting in the panel header.

Because if you load the page for the first time after a couple of days it will show data from a couple of days ago as if it's fresh. Then if you wait a few seconds it will rerender with the latest data. But there is not indication that is what is happening.

**Comment by cmichi** [comment]
Hi @chatch,

can you explain how to reproduce this issue? I'm not sure if I understand correctly what you mean with this:

> Because if you load the page for the first time after a couple of days it will show data from a couple of days ago as if it's fresh. Then if you wait a few seconds it will rerender with the latest data.

Could it be that this issue is no longer present in the current master because of this commit: https://github.com/chatch/stellarexplorer/commit/65177bbfe61d68de72fae9efe0f2339c66931783?

Thanks!

**Comment by cmichi** [comment]
I think the issue of outdated data being displayed can still happen. At the moment the stream is automatically timed out after three minutes, so a user has possibly outdated data displayed after that time. 

Maybe we could occasionally check if there is new data available and if so display the green/red light you suggested and re-create the stream?

**Comment by chatch** [comment]
actually i havn't seen this happen for months so yeah it seems it has gone away. i can't remember why it was happening previously but i don't think the commit above was the fix. might have been changes to the way  the DataFetchingContainer works.

the case where we stop fetching new records after 3 minutes i don't know if it's worth it ...?  it's probably obvious that's what's happened in this case.  i think ... users can do a page refresh or navigate away and back to the view if they want to get fresh records.
