### ISSUE TITLE
I don't recived xlm in my wallet

### ISSUE THREAD

**Issue by momonono16** [chatch/stellarexplorer#290]
![Screenshot_20210512-082409_BitMart](https://user-images.githubusercontent.com/84043509/117904881-602d0d00-b2fc-11eb-91e5-5a3547c6e029.jpg)

I don't received my xlm from bitkub to Binance at 
635.0350381 XLM
![Screenshot_20210512-082500_Gmail](https://user-images.githubusercontent.com/84043509/117904953-85218000-b2fc-11eb-92dd-c70248d845bb.jpg)
![Screenshot_20210512-082513_Chrome](https://user-images.githubusercontent.com/84043509/117904970-8e125180-b2fc-11eb-8b2b-ccdf461e0cba.jpg)
coins. I found the link show error not found. Please let me know if you need more details and suggest me for the feedback. Thanks for your support in advance.

**Comment by cmyers1217** [comment]
I did not receive my XLM into Lobstr from Coinbase Wallet. It shows transaction on Stellar Explorer.

**Comment by natty123456** [comment]
อยากทราบว่าพี่ได้คืนยังคะ
