### ISSUE TITLE
Funds not recvd at Bitmart (double check on this end)

### ISSUE THREAD

**Issue by alreadyda1** [chatch/stellarexplorer#303]
###  Please NOTE the following before creating an issue:

WE CAN'T HELP WITH FUNDS NOT RECEIVED, DELAYED OR WRONG MEMOS - CONTACT THE EXCHANGE OR THE RECEIPIENT IN THESE CASES - Stellar Explorer IS JUST A READ ONLY VIEW OF THE LEDGER

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

**Comment by alreadyda1** [comment]
I requested my XLM be transferred to bitmart. Please check this end to help me. I have over $1000 missing and I keep getting nothing with chat bots. Is it possible the transaction had an error? Anything would help. This was done yesterday morning.

**Comment by Jessicadrichardson** [comment]
I

**Comment by Jessicadrichardson** [comment]
I

**Comment by Jessicadrichardson** [comment]
I

**Comment by Jessicadrichardson** [comment]
I

**Comment by Jessicadrichardson** [comment]
I
