### ISSUE TITLE
Just transferred XLm from Coinbase wallet to Coinbase pro and it’s not showing up

### ISSUE THREAD

**Issue by orozco014** [chatch/stellarexplorer#304]
###  Please NOTE the following before creating an issue:

WE CAN'T HELP WITH FUNDS NOT RECEIVED, DELAYED OR WRONG MEMOS - CONTACT THE EXCHANGE OR THE RECEIPIENT IN THESE CASES - Stellar Explorer IS JUST A READ ONLY VIEW OF THE LEDGER

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

**Comment by orozco014** [comment]
I Transferred some XLM from my Coinbase wallet to my Coinbase pro and have not received it. It say the transfer was successful

**Comment by Jessicadrichardson** [comment]
@orozco014
