### ISSUE TITLE
Wallet to exchange transfer

### ISSUE THREAD

**Issue by elpanzon6** [chatch/stellarexplorer#311]
I transferred my stellar lumens from my coin base wallet to my Binance￼ US account and it's not showing on either account can you help me with this￼

**Comment by elpanzon6** [comment]
![image](https://user-images.githubusercontent.com/86507325/124015583-124e9000-d9a2-11eb-9af4-34f7c25b847b.png)

**Comment by elpanzon6** [comment]
![image](https://user-images.githubusercontent.com/86507325/124015609-1aa6cb00-d9a2-11eb-9476-7763c4fdb7a8.png)

**Comment by elpanzon6** [comment]
![image](https://user-images.githubusercontent.com/86507325/124019140-e7663b00-d9a5-11eb-82ea-6df8b79dc4a4.png)

**Comment by loydie28** [comment]
how to received

**Comment by elpanzon6** [comment]
I'm not understanding I have not received my funds in my Binance.US how do I get it

**Comment by chatch** [comment]
did you send it to the wrong deposit address or wrong memo possibly? you can check it the that in the transaction details on in Stellar Explorer.

if it's the correct address and memo then you need to contact binance to see why it hasn't shown up in your account ...

**Comment by elpanzon6** [comment]
I transferred all my crypto the exact same way and my biggest account was
the one that did not get transferred I’ve been trying to get a hold of
Binance.US I have not heard nothing back from them do you recommend an
exchange that’s good
