### ISSUE TITLE
Not received funds to coinbase account exchange 

### ISSUE THREAD

**Issue by Daveful** [chatch/stellarexplorer#312]
![Screenshot_2021-07-08-21-36-19-66](https://user-images.githubusercontent.com/87146206/124987361-b1275c00-e034-11eb-991c-28916de711e6.jpg)
###  Please NOTE the following before creating an issue:

WE CAN'T HELP WITH FUNDS NOT RECEIVED, DELAYED OR WRONG MEMOS - CONTACT THE EXCHANGE OR THE RECEIPIENT IN THESE CASES - Stellar Explorer IS JUST A READ ONLY VIEW OF THE LEDGER

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

**Comment by chatch** [comment]
> WE CAN'T HELP WITH FUNDS NOT RECEIVED, DELAYED OR WRONG MEMOS - CONTACT THE EXCHANGE OR THE
> RECEIPIENT IN THESE CASES - Stellar Explorer IS JUST A READ ONLY VIEW OF THE LEDGER

as mentioned we can't help with these cases. the only thing you can do is contact the receiver coinbase to find out why they havn't processed it for you. the funds are with them ...
