### ISSUE TITLE
I sent XLM from my Coinbase Wallet to Coinbase but didn’t know I had to complete the memo line. Now it’s not showing up in either place.  Here is the transaction:

### ISSUE THREAD

**Issue by marcos-nin** [chatch/stellarexplorer#315]
I sent XLM from my Coinbase Wallet to Coinbase but didn’t know I had to complete the memo line. Now it’s not showing up in either place.

Here is the transaction:

GDQP2KPQGKIHYJGXNUIYOMHARUARCA7DJT5FO2FFOOKY3B2WSQHG4W37

**Comment by marcos-nin** [comment]
![AF001E5F-CD97-4C9C-A5EC-E45D5FCF2A2F](https://user-images.githubusercontent.com/87553950/126022124-b26ad328-7a49-4692-a5e7-2d7bba82c606.png)

**Comment by mezzg** [comment]
> I sent XLM from my Coinbase Wallet to Coinbase but didn’t know I had to complete the memo line. Now it’s not showing up in either place.
> 
> Here is the transaction:
> 
> GDQP2KPQGKIHYJGXNUIYOMHARUARCA7DJT5FO2FFOOKY3B2WSQHG4W37

I habe the same prob

**Comment by y0st22** [comment]
I did the exact same thing today. Is there a solution?

**Comment by mezzg** [comment]
i dont think so :/

tis 31 aug. 2021 kl. 02:15 skrev y0st22 ***@***.***>:
