### ISSUE TITLE
Hi I send stellar from Coinbase wallet to Crypto.com with out memo and it’s not receive so what can I do?

### ISSUE THREAD

**Issue by Sardadht73** [chatch/stellarexplorer#328]
[]() ###  Please NOTE the following before creating an issue:

WE CAN'T HELP WITH FUNDS NOT RECEIVED, DELAYED OR WRONG MEMOS - CONTACT THE EXCHANGE OR THE RECEIPIENT IN THESE CASES - Stellar Explorer IS JUST A READ ONLY VIEW OF THE LEDGER

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

**Comment by jarysanchezz** [comment]
Hi I send stellar from Coinbase wallet to BitMart account with out memo and it’s not receive so what can I do?
