### ISSUE TITLE
Fund not recieved

### ISSUE THREAD

**Issue by Bhanuanu** [chatch/stellarexplorer#329]
![Screenshot_2021-10-02-10-36-32-314_com android chrome](https://user-images.githubusercontent.com/91772119/135704351-ac7abfac-8ada-44cf-a1a1-ce8bcca5b69d.jpg)
![Screenshot_2021-10-02-10-36-18-962_com android chrome](https://user-images.githubusercontent.com/91772119/135704352-3519d9e7-5802-4ed9-b83b-92bb414fe657.jpg)

GDDLBDK6MPELQT5O6QC7BT56SM3WQKY7PEJ7FI4LQECDEZFTUB2JSKVC
Memo : 480544
![Screenshot_2021-10-02-10-37-41-013_com android printspooler](https://user-images.githubusercontent.com/91772119/135704347-9e175cbd-4c6e-45d4-bebf-b273eebb39ba.jpg)

**Comment by emar1234** [comment]
Fund not received as well how do we get it back

**Comment by Bhanuanu** [comment]
Not respond 10 days over

**Comment by Bigred331** [comment]
Sorry brother had a few issues
