### ISSUE TITLE
Need help with transfer without memo

### ISSUE THREAD

**Issue by Shurlarmc** [chatch/stellarexplorer#344]
I need help getting back the transfer as i didn’t put the memo work I put in the XLM address but didn’t put the memo

**Comment by shafiqnr4** [comment]
GAHK7EEG2WWHVKDNT4CEQFZGKF2LGDSW2IVM4S5DP42RBW3K6BTODB4A

1064645590

**Comment by Doichoai2001** [comment]
I trade wrong @ kucoin from stellar , how I send back ?
