### ISSUE TITLE
I must have need a memo to send to Coinbase. My xlm has never showed up 

### ISSUE THREAD

**Issue by Tethomps1483** [chatch/stellarexplorer#345]
###  Please NOTE the following before creating an issue:

WE CAN'T HELP WITH FUNDS NOT RECEIVED, DELAYED OR WRONG MEMOS - CONTACT THE EXCHANGE OR THE RECEIPIENT IN THESE CASES - Stellar Explorer IS JUST A READ ONLY VIEW OF THE LEDGER

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

**Comment by flowerpete** [comment]
I transferred some money to this account I never seen those funds show up please help me

**Comment by Arronn77** [comment]
Same here

**Comment by hotCoz-xuqziq-didvo1** [comment]
What should I do to get my money back
