### ISSUE TITLE
I need help getting back the transfer as i didn’t put the memo work I put in the XLM address but didn’t put the memo  no received for binance please 🙏 help address GAHK7EEG2WWHVKDNT4CEQFZGKF2LGDSW2IVM4S5DP42RBW3K6BTODB4A MEM 1064645590 O 

### ISSUE THREAD

**Issue by shafiqnr4** [chatch/stellarexplorer#350]
###  Please NOTE the following before creating an issue:

WE CAN'T HELP WITH FUNDS NOT RECEIVED, DELAYED OR WRONG MEMOS - CONTACT THE EXCHANGE OR THE RECEIPIENT IN THESE CASES - Stellar Explorer IS JUST A READ ONLY VIEW OF THE LEDGER

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

**Comment by veryupset9** [comment]
You don't need a memo
