### ISSUE TITLE
I didn't put in a memo and so funds weren't received, please advise.

### ISSUE THREAD

**Issue by Fabby1d** [chatch/stellarexplorer#351]
###  Please NOTE the following before creating an issue:

WE CAN'T HELP WITH FUNDS NOT RECEIVED, DELAYED OR WRONG MEMOS - CONTACT THE EXCHANGE OR THE RECEIPIENT IN THESE CASES - Stellar Explorer IS JUST A READ ONLY VIEW OF THE LEDGER

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

**Comment by multime123** [comment]
Hi please I have made a transfer from Coinbase to Crypto.com. And I didn’t put the memo code . And I haven’t reserved my xlm please cancel this transfer and return my xlm to Coinbase. Please I am sorry for my mistake
