### ISSUE TITLE
I need help getting back the transfer as i wrong put the memo

### ISSUE THREAD

**Issue by Chanchayutbank** [chatch/stellarexplorer#358]
I need help getting back the transfer as i wrong put the memo work I put in the XLM address but didn’t put the memo no received for bitkub please 🙏 help 
address GBS2RTBGEWBT7DJOH7CTA4PDVLIPONCPCIILJPPESWSHDIV4NFZJHRP3
memo :  1031367030

![0604925B-1F80-4FCA-A331-0E47EF7D0B41](https://user-images.githubusercontent.com/94023499/141026559-3f0bce6e-f76a-4eef-b3b9-37c43c4e3486.png)
![6453A837-B252-4F9D-B16A-D9FF5739BD3E](https://user-images.githubusercontent.com/94023499/141026568-ffb4a8b4-2243-4168-9cbd-ea0ec1f8eebd.png)
![76E2CD0F-0828-4F13-A257-5291181BF228](https://user-images.githubusercontent.com/94023499/141026571-0032067b-473b-48dc-9ced-f6a8836dc63a.png)

**Comment by Chanchayutbank** [comment]
Help please.

**Comment by KINGBEBETHEBOSS** [comment]
Help please I need help getting back the transfer as i wrong put the memo work I put in the XLM address but didn’t put the memo
