### ISSUE TITLE
XLM Payment in progress since yesterday

### ISSUE THREAD

**Issue by hr12465** [chatch/stellarexplorer#361]
###  Please NOTE the following before creating an issue:

WE CAN'T HELP WITH FUNDS NOT RECEIVED, DELAYED OR WRONG MEMOS - CONTACT THE EXCHANGE OR THE RECEIPIENT IN THESE CASES - Stellar Explorer IS JUST A READ ONLY VIEW OF THE LEDGER

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

**Comment by hr12465** [comment]
XLM Payment in progress since yesterday. What is going on????

**Comment by veryupset9** [comment]
Mine too. It gave me a hash. But it is I valid. I commented #368 #369 #370.  How do you contact these people.
