### ISSUE TITLE
Sent XML WITH NO MEMO

### ISSUE THREAD

**Issue by Kelvisp94** [chatch/stellarexplorer#365]
###  Please NOTE the following before creating an issue:

WE CAN'T HELP WITH FUNDS NOT RECEIVED, DELAYED OR WRONG MEMOS - CONTACT THE EXCHANGE OR THE RECEIPIENT IN THESE CASES - Stellar Explorer IS JUST A READ ONLY VIEW OF THE LEDGER

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

**Comment by anilk666** [comment]
WE  HELP WITH FUNDS NOT RECEIVED, DELAYED OR WRONG MEMOS - CONTACT THE EXCHANGE OR THE RECEIPIENT IN THESE CASES - Stellar Explorer IS JUST A READ ONLY VIEW OF THE LEDGER

**Comment by veryupset9** [comment]
You Don't need a memo .

**Comment by veryupset9** [comment]
Did get this resolved. I feel we will not be helped. As there are millions of transactions
