### ISSUE TITLE
can't check transection and not recieved

### ISSUE THREAD

**Issue by Soulmooo** [chatch/stellarexplorer#366]
###  Please NOTE the following before creating an issue:

WE CAN'T HELP WITH FUNDS NOT RECEIVED, DELAYED OR WRONG MEMOS - CONTACT THE EXCHANGE OR THE RECEIPIENT IN THESE CASES - Stellar Explorer IS JUST A READ ONLY VIEW OF THE LEDGER

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

## 
I can't check transection and not recieved xlm
![SmartSelect_20211204-133516_Outlook](https://user-images.githubusercontent.com/95519695/144700444-534a8159-b774-450b-bbd4-a74b2ec15be5.jpg)

**Comment by veryupset9** [comment]
I had the same issue. I commented.  #368#369 and #370
