### ISSUE TITLE
I can't check transection and not recieved xlm https://steexp.com/tx/d345bfe93946b04c157c10bc4c76bbaf2192ffee0e5353ec9aba991ce1cf5bec

### ISSUE THREAD

**Issue by PhayaoPro** [chatch/stellarexplorer#367]
###  Please NOTE the following before creating an issue:

WE CAN'T HELP WITH FUNDS NOT RECEIVED, DELAYED OR WRONG MEMOS - CONTACT THE EXCHANGE OR THE RECEIPIENT IN THESE CASES - Stellar Explorer IS JUST A READ ONLY VIEW OF THE LEDGER

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

**Comment by veryupset9** [comment]
this happend to me today.  Invalid hash . Missing xlm.. I was provided a hash but it is missing
