### ISSUE TITLE
Help me! 

### ISSUE THREAD

**Issue by Sezocoin** [chatch/stellarexplorer#381]
Good day, I transferred about $29 worth of XLM coin from the wallet application at 20:50 yesterday evening to binance TR, but the transfer did not arrive and it does not appear in my wallet. I request help.

**Comment by CryptoNista** [comment]
the same for me using rabet wallet to exchanhe rabet. the transfer did not arrive till 8 hours ago

**Comment by Hariommeena123** [comment]
25 h bad Kar na yaar
