### ISSUE TITLE
Transaction error.

### ISSUE THREAD

**Issue by bono5986** [chatch/stellarexplorer#384]
Yesterday, the withdrawal was made to the address below, but an error occurred. Please solve it.

ID :  NXTkgVKfzPYlg

Wallet AD : GDU77IKPQK74COCEM6HYAX7IMAGCC2IVNDPLW7N7GL2GSSTNMYPMXE7X

**Comment by thip74** [comment]
please help me  The coin transfer hasn't arrived yet.
wallet :
GBS2RTBGEWBT7DJOH7CTA4PDVLIPONCPCIILJPPESWSHDIV4NFZJHRP3

**Comment by Puttirong** [comment]
please help me The coin transfer hasn't arrived yet wallet : GAWPTHY6233GRWZZ7JXDMVXDUDCVQVVQ2SXCSTG3R3CNP5LQPDAHNBKL
