### ISSUE TITLE
HELP! 

### ISSUE THREAD

**Issue by Kawa44** [chatch/stellarexplorer#389]
###  Please NOTE the following before creating an issue:

MY XLM İS LOST / ı just transfer from MEXC Global
to binance but ı didnt use memo than now ı kost my xlm help me GAHK7EEG2WWHVKDNT4CEQFZGKF2LGDSW2IVM4S5DP42RBW3K6BTODB4A
WE CAN'T HELP WITH FUNDS NOT RECEIVED, DELAYED OR WRONG MEMOS - CONTACT THE EXCHANGE OR THE RECEIPIENT IN THESE CASES - Stellar Explorer IS JUST A READ ONLY VIEW OF THE LEDGER
![resim_2022-01-03_101655](https://user-images.githubusercontent.com/97016505/147906835-35db84e9-ad90-4fab-816d-8529e13145a6.png)

**Comment by Kawa44** [comment]
rewrite. MY XLM İS LOST / ı just transfer from MEXC Global
to binance but ı didnt use memo than now ı kost my xlm help me GAHK7EEG2WWHVKDNT4CEQFZGKF2LGDSW2IVM4S5DP42RBW3K6BTODB4A

**Comment by CaptsinDin** [comment]
GAXSPKGPLZ2KBAOTC4EKZ4HXAPU3J5KCGCYG5NHJNG4PWELLBSGQ65MK 
I entered tag the wrong.
Key tag wrong 1059118556
tag correct 8670114749887
