### ISSUE TITLE
Clean up mobile views

### ISSUE THREAD

**Issue by chatch** [chatch/stellarexplorer#52]
Some pretty crazy formatting, wrapping, etc. when I view it on a standard sized android mobile.

Ensure everything fits neatly. Avoid scrolling etc.

**Comment by stellarstyler** [comment]
Hey I've been looking at some of the formatting issues for the table. Haven't tested it fully but adding the rules, table-layout: fixed, width: 100% to the #operation-table id will fix the rows overflowing for that particular table. I'm planning on adding some media queries for text size for different device dimensions to reduce the height of the rows. I should have a more thorough solution in the next few days.

**Comment by chatch** [comment]
that'd be great. btw. i had a look at the search box on mobile which is overflowing on small widths. I tried to get it doing 100% (flexible) width but I couldn't. some css parent rule maybe that is overriding the width ...?  if you get a chance could you take a look at that?

**Comment by chatch** [comment]
#56

**Comment by chatch** [comment]
merged #56
