### ISSUE TITLE
WHILE WE MINE PI NETWORK THE INACTIVE PIONEERS BALANCE GET REDUCED AFTER LONG TIME MINING 

### ISSUE THREAD

**Issue by narayankunwar2020** [chatch/stellarexplorer#520]
WHILE WE ARE MINING PI NETWORK THE PIONEERS WHOSE ACCOUNT IS INACTIVE FOR LONGER PERIOD OF TIME AFTER THE PIONEER ACTIVES THAT ACCOUNT AFTER LONGER PERIOD OF TIME THERE ARE LOGIN ISSUES AND W E CANNOT RETIIVE OUR MINED PI BEFORE AND PLS SOLVE THIS ISSUES IS IT POSSIBLE TO SOLVE IT FROM THIS PLS

**Comment by chatch** [comment]
this software is unrelated to pi network.  you can raise this issue on their repository
