### ISSUE TITLE
Missing CUSTOM option

### ISSUE THREAD

**Issue by marco5846** [chatch/stellarexplorer#527]
Today I found out that on https://steexp.com/ has been removed the option to explore a custom blockchain. 

Is it possible to restore this option?

**Comment by chatch** [comment]
when I get time to fix this in the latest version deployed at steexp.com I'll comment on this issue. thanks for raising it.

**Comment by chatch** [comment]
@marco5846 finally fixed this issue, see #564 

deploying the fix now so please try it out and let me know if you have any issues. you'll note there is an extra address now for the soroban RPC.
