### ISSUE TITLE
KYC

### ISSUE THREAD

**Issue by Nanda442998** [chatch/stellarexplorer#532]
My username-@442998
I am waiting for last 3 years KYC...
![Screenshot_2023-09-14-07-07-25-861_pi browser](https://github.com/chatch/stellarexplorer/assets/86641947/14a7e5e9-4ddf-4351-8876-b628baa4b407)
![Screenshot_2023-09-14-07-07-06-022_com blockchainvault](https://github.com/chatch/stellarexplorer/assets/86641947/f4d6c16a-ba68-4ab1-b921-c97625c277f3)

**Comment by 123321famou** [comment]
@Nanda442998 kyc的算法似乎有些问题，这导致更多人无法及时收到kyc的邀请！这让人很沮丧，这甚至让他们只是炉边论坛的观众而非参与者，这也导致他们对炉边论坛失去了主动参与的兴趣

**Comment by jayvelante** [comment]
Hello team😍

My Pi network account is not invite for KYC.. Since August 12, 2019.

Username jayvelante please help me😔. Thank you❤️

**Comment by jayvelante** [comment]
![Screenshot_20230924_074825_com blockchainvault](https://github.com/chatch/stellarexplorer/assets/97501482/df4ca177-037f-4c8a-b030-a964705ccae6)

**Comment by jayvelante** [comment]
![Uploading Screenshot_20230924_074931_pi.browser.jpg…]()

**Comment by jayvelante** [comment]
![Uploading Screenshot_20230924_074931_pi.browser.jpg…]()

**Comment by jayvelante** [comment]
![Screenshot_20230924_074931_pi browser](https://github.com/chatch/stellarexplorer/assets/97501482/32fde87f-b724-4089-8a8a-f7456328fc2c)

**Comment by Showmethemoney62** [comment]
I was invited to apply for KYC 5 days ago but waited 2 months. Actually my invitation came right after my 40th invitation for pioneers was sent out. I've been reading some stories about people waiting one, two and as much as three years before being validated. I don't think I could stand it. I was told that depending on the amount of validators in your area determines the expedition of your verification.

**Comment by chatch** [comment]
this repository is unrelated to pi and the pi explorer repository. it's only for stellar explorer and the stellar network.

**Comment by chengchangwei123** [comment]
我的kyc第七项已经一年半了，到目前为止还是一个○。我的用户名是@chengchangwei
