### ISSUE TITLE
Explorer

### ISSUE THREAD

**Issue by Picio99** [chatch/stellarexplorer#539]
When you go to

https://blockexplorer.minepi.com/

is displayed the search bar. If you search a wallet that didn't exist the explorer is not usable in any way(no other tab, no refresh, also if you go back)

it create automatically

https://blockexplorer.minepi.com/error/general/network

ans is impossible to go throught and make another search

I tried with GDAL3E5AHY3ADFEMU7SHUX3NY6JSUQBBM3EZ4RTSCLHOZDBHPFMELSD7

**Comment by chatch** [comment]
raise this on piexplorer repo. this is for stellar.
