### ISSUE TITLE
New liquidity pools listing and views

### ISSUE THREAD

**Issue by chatch** [chatch/stellarexplorer#540]
Liquidity pools:
- new page liquidity pool listing – all liquidity pools listing
- new page liquidity pool details – show trades, ops, etc. related to the pool
- add top menu item to navigate to here
- add pool id to search?

**Comment by jp-ryuji** [comment]
Implemented at:
https://github.com/chatch/stellarexplorer/pull/557
https://github.com/chatch/stellarexplorer/pull/581
