### ISSUE TITLE
Add search by asset code and anchor name

### ISSUE THREAD

**Issue by chatch** [chatch/stellarexplorer#57]

**Comment by chatch** [comment]
search by substring of anchor name works
search by asset code works however in the event of more than one issuer for an asset (eg. BTC) it is navigating to the first one only - so change this to show a list of matching assets.

**Comment by chatch** [comment]
![search by asset code](https://github.com/chatch/stellarexplorer/blob/3276902542dca7186aadbd31d09b70310aae9a0a/screenshots/search_by_asset.png)

**Comment by chatch** [comment]
![search by anchor](https://raw.githubusercontent.com/chatch/stellarexplorer/3276902542dca7186aadbd31d09b70310aae9a0a/screenshots/search_by_anchor.png)

**Comment by Thompson1985** [comment]
Great job
