### ISSUE TITLE
Made a transfer without the memo in the description.

### ISSUE THREAD

**Issue by gunner99** [chatch/stellarexplorer#573]
###  Please NOTE the following before creating an issue:

WE CAN'T HELP WITH FUNDS NOT RECEIVED, DELAYED OR WRONG MEMOS - CONTACT THE EXCHANGE OR THE RECEIPIENT IN THESE CASES - Stellar Explorer IS JUST A READ ONLY VIEW OF THE LEDGER

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

**Comment by gre3n3yes34** [comment]
No I  need an withdrawal  button  on the website.

**Comment by chatch** [comment]
as mentioned in the issue template we can't do anything about these issues
