### ISSUE TITLE
Accounts page tab subtitles not rendering

### ISSUE THREAD

**Issue by chatch** [chatch/stellarexplorer#577]
Since upgrading remix to v2 the account page titles don't change when the tabs change.

For example we used to see `Stellar Explorer | Account Balances` but now it will say `Stellar Explorer | Account`. 

It appears that the tab title is rendered briefly but then the parent resets the title again...

NOTE: when this is fixed the playwright smoke tests will need updating to reflect the title seen again...

**Comment by jp-ryuji** [comment]
Fixed at https://github.com/chatch/stellarexplorer/pull/578 and the smoke test was reverted at https://github.com/chatch/stellarexplorer/pull/579
