### ISSUE TITLE
Transfer stellar lumens transaction to crypto.com account

### ISSUE THREAD

**Issue by RNANOS** [chatch/stellarexplorer#590]
###  Please NOTE the following before creating an issue:

WE CAN'T HELP WITH FUNDS NOT RECEIVED, DELAYED OR WRONG MEMOS - CONTACT THE EXCHANGE OR THE RECEIPIENT IN THESE CASES - Stellar Explorer IS JUST A READ ONLY VIEW OF THE LEDGER

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

**Comment by RNANOS** [comment]
GCDWX5FM3ZEABJTRBQVIFFAGMJKXG64O2BEC7464MA5G5A4DNNGHTHKV

This got transferred to stellar explorer public account instead of crypto.com Xlm account. How do I transfer it out

**Comment by chatch** [comment]
what does " stellar explorer public account " mean? is it an account you own? if so you can transfer out of it but if you don't own it (have the private keys) then you can not.

**Comment by RNANOS** [comment]
This is the account it went into from your site. No I do not have a stellar
lumens Xlm account.

When I pressed deposit Xlm these from my crypto.com account this is where
it said to send it
