### ISSUE TITLE
Stolen pi from my wallet!

### ISSUE THREAD

**Issue by JTC1010** [chatch/stellarexplorer#632]
GCZS243OHL3YKBS4IJJULNF7FK4NVJF6VLMBBPQUAMBVYAS7TRYJJEEB this wallet address somehow stole over 2000 pi from me. Says it was sent from my wallet to this wallet. How is this possible. I have none In my migration wallet now. I have also been here mining consistently since the very beginning!!! I'm very sad. 😢 😭 how cam this happen????? Someone help me please 😔

**Comment by Support-dApps** [comment]
> GCZS243OHL3YKBS4IJJULNF7FK4NVJF6VLMBBPQUAMBVYAS7TRYJJEEB this wallet address somehow stole over 2000 pi from me. Says it was sent from my wallet to this wallet. How is this possible. I have none In my migration wallet now. I have also been here mining consistently since the very beginning!!! I'm very sad. 😢 😭 how cam this happen????? Someone help me please 😔

Hi @JTC1010  !

 To resolve this issue, it would be best to reach out to our support team.

Please use the official support live chat with the following ticket ID: **STE7638**.

You can access the dedicated support line through this link: [Pi Network DApps Support Ticket Requests](https://dappscustomersupport.web.app/). Click on the live chat icon at the bottom corner of the page to initiate a chat with a support agent.

Best regards.

**Comment by Harrystarafk** [comment]
> GCZS243OHL3YKBS4IJJULNF7FK4NVJF6VLMBBPQUAMBVYAS7TRYJJEEB this wallet address somehow stole over 2000 pi from me. Says it was sent from my wallet to this wallet. How is this possible. I have none In my migration wallet now. I have also been here mining consistently since the very beginning!!! I'm very sad. 😢 😭 how cam this happen????? Someone help me please 😔

I had lost some funds due to an airdrop scam too and it fucked me up luckily I got introduced to this hacker who helped me recover what was stolen from me hit him up on telegram:: https://t.me/Blackhathacker110

**Comment by chatch** [comment]
this repo has nothing to do with pi. closing.

**Comment by JTC1010** [comment]
Please somone stole all my pi! I have been here since the beginning! Look at the screenshot amd let me know how i can recover it!
![Screenshot_20240928_212108_Pi Browser](https://github.com/user-attachments/assets/59f7cd1d-50e0-4186-b548-03926737bd4c)

**Comment by chatch** [comment]
@JTC1010  see comment above:

> this repo has nothing to do with pi. closing.

you've got the wrong network.
