### ISSUE TITLE
Transaction JSON got broken

### ISSUE THREAD

**Issue by s-a-y** [chatch/stellarexplorer#64]
After the latest update transaction JSON doesn't show anything (link Transaction details also doesn't lead anywhere)
<img width="634" alt="screen shot 2018-03-16 at 10 33 26 pm" src="https://user-images.githubusercontent.com/1667781/37518667-3ba840fe-296a-11e8-81b3-2a90902c10ef.png">

**Comment by chatch** [comment]
thanks for reporting this. I've just deployed a fix.

**Comment by s-a-y** [comment]
That was fast 👍
