### ISSUE TITLE
Beatus47

### ISSUE THREAD

**Issue by Beatus47** [chatch/stellarexplorer#644]
###  Please NOTE the following before creating an issue:

WE CAN'T HELP WITH FUNDS NOT RECEIVED, DELAYED OR WRONG MEMOS - CONTACT THE EXCHANGE OR THE RECEIPIENT IN THESE CASES - Stellar Explorer IS JUST A READ ONLY VIEW OF THE LEDGER

If your issue is with steexp.com itself or you have any suggestion or comment please enter the details below. Thank you!

## Issue Description
I am going loss all coin pi 900. Because KYC is not complete and still waiting more than 2 year is not succes.

**Comment by chatch** [comment]
this repo has nothing to do with pi
