### ISSUE TITLE
Wrong behaviour of Previous page button

### ISSUE THREAD

**Issue by s-a-y** [chatch/stellarexplorer#65]
When you go through payments using button "Next page" it moves to next page: page 1 -> page 2 -> page 3 -> page 4...

When you trying to come back using "Previous page" button it behaves as browser back button: page4 -> page3 -> page4 -> page3...

<img width="1440" alt="screen shot 2018-04-06 at 3 02 13 pm" src="https://user-images.githubusercontent.com/1667781/38404202-b26f2332-39ab-11e8-9161-40ea257dbd52.png">

**Comment by chatch** [comment]
Thanks for reporting this.

Looks like it's also a problem on the "Effects" tab.
Possibly on "Offers" also - I'll try find or make an account with heaps of offers.
Not a problem on the "operations" and "transactions" tabs - working fine for me there.

**Comment by chatch** [comment]
occuring on the top level view also: https://steexp.com/payments
