### ISSUE TITLE
scam

### ISSUE THREAD

**Issue by Ahmadss85ss** [chatch/stellarexplorer#657]
Welcome My wallet was hacked and the pi in it was transferred to a series of different accounts In the end, it flows into an account containing a large number of currency I ask for help. I was not the one who referred them. They have worked hard for years, and I have been a believer in the project since the beginning. I ask for help. I have submitted more than one report to Cortim, but I have not received any help. Please note that I provided full details and attached photos Fraud address GCCVAOIXE3OR33S3BIINRBW54LU2BOADTGI2FLKSA2FWCCPMBW2DIWEU JSON 84c4f72144bd0391ab1309162c40b617cdf45233da657c92b4dcca694291cd3e Please follow and help please Especially since I made a reservation for the remaining quantity until 2026 Can I transfer this process to the new wallet for fear of theft? Please help me user name ahmadss85@

**Comment by chatch** [comment]
this repo has nothing to do with pi
