### ISSUE TITLE
Stole pi from my wallet!! See screenshot! Please help

### ISSUE THREAD

**Issue by JTC1010** [chatch/stellarexplorer#665]
![Screenshot_20240928_212108_Pi Browser](https://github.com/user-attachments/assets/e7431fd7-4eca-4ccb-b532-cf3094606b72)
Someone help me recover my pi please!

**Comment by Jomossey** [comment]
@JTC1010 It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID PI07638
Please see the link below to our dedicated support line:
[Pi blockexplorer Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by chatch** [comment]
right this repo has nothing to do with pi at all so you won't get any help here.
