### ISSUE TITLE
CSV export feature

### ISSUE THREAD

**Issue by chatch** [chatch/stellarexplorer#67]
For main operations / transactions / effects views
For account tabs: as above plus payments, offers, ...

**Comment by cmichi** [comment]
Hi @chatch,

I'm interested in implementing this and quickly want to clarify if I understand the idea correctly: The intention is to add a CSV export button everywhere where it currently is only possible to export JSON by clicking the JSON badge button, correct?

Thanks! Michael

**Comment by chatch** [comment]
hi @cmichi, great!  

yeah i was thinking anywhere there is a list it would be useful. especially on the account page tabs like payments, trades, effects, etc. people could easily export their transactions.  on other list views it's a nice to have to get the data out in another way.

so yeah another button for CSV that will direct download (rather then show in a modal like the JSON / TOML ones).
