### ISSUE TITLE
Need help - Need some resources

### ISSUE THREAD

**Issue by tfhdevelopment** [chatch/stellarexplorer#95]
Looking to implement this into a website for a forked coin of stellar.

My vps has WHM and want to set this up in a sub-domain, I'm not even sure if its possible this way?

Just looking for what kind of information i need to make this happen, there is not many guides specific to block explorers, so generic information that will help would be brilliant!

My understanding so far is installing the dependencies on the server, uploading the files and configuring them but somehow i really doubt its that easy. 

I'm young and new to coding but hoping a project like this can help me learn so any help is greatly appreciated!

**Comment by chatch** [comment]
Hi @tfhdevelopment, no worries, yes take a look at this link for some ways to deploy the application: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#deployment

the site is a create-react-app app so these instructions apply to the stellarexplorer also.

to summarise you build the entire site into a static bundle with "npm run build".  the entire site is under build/ after this.  put that under a webserver somewhere and you'll be good to go.  in my case i use heroku with the a staticbuild back but there are many options.
