### ISSUE TITLE
Xlm stellar Help!!! 

### ISSUE THREAD

**Issue by Obscur87** [chatch/stellarexplorer#96]
please help me to return the funds in the amount of 700.163 xlm yesterday sent to another wallet and did not come
Thid: 23cb6bcaa3e1977ef6149858ae3557cf29a0c7635887828540e8e0e36679897f

**Comment by Obscur87** [comment]
Help me

**Comment by Obscur87** [comment]
Help me

**Comment by chatch** [comment]
https://steexp.com/tx/23cb6bcaa3e1977ef6149858ae3557cf29a0c7635887828540e8e0e36679897f

can see there was a  payment to: GCXELQ66PJPXSJL3CWVGGH2OXJSFNBDMTTBK6CNBNAR4WKAITLLSLKBU

**Comment by Obscur87** [comment]
forgot to specify the tag

**Comment by Obscur87** [comment]
forgot to specify the tag9:58, 19 августа 2018 г., Chris Hatch <notifications@github.com>:https://steexp.com/tx/23cb6bcaa3e1977ef6149858ae3557cf29a0c7635887828540e8e0e36679897f
can see there was a  payment to: GCXELQ66PJPXSJL3CWVGGH2OXJSFNBDMTTBK6CNBNAR4WKAITLLSLKBU

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail

**Comment by chatch** [comment]
oh i see. you forgot to add the memo right?

you can't change this after the fact.  that transaction is done.  you'd need to contact whoever the GCXE... address owner is if you want it returned.

**Comment by Obscur87** [comment]
and how to contact him? please tell me

**Comment by chatch** [comment]
i don't know who that address belongs too ...
